### ISSUE TITLE
Error "Only a single prefetcher is allowed per script."

### ISSUE THREAD

**Issue by pinterf** [AviSynth/AviSynthPlus#103]
Avisynth terminates with "Only a single prefetcher is allowed per script."
Avs+ version MT 2172 is surely affected

```
ColorbarsHD()
nnedi3_rpow2(2, Threads=1)
Prefetch(1)
```

Use nnedi3 0.9.4.29 from here: http://forum.doom9.org/showthread.php?t=170083
I think the error is not nnedi3 specific.

Other report:
http://forum.doom9.org/showthread.php?p=1779369#post1779369

**Comment by pinterf** [comment]
Tried a hotfix, there must be a smarter way
https://github.com/AviSynth/AviSynthPlus/pull/101/commits/ffe50717199374196002864aecfe4997ccd08235

**Comment by Reel-Deal** [comment]
Just adding these links for reference:
- http://forum.doom9.org/showthread.php?p=1784367#post1784367
- http://forum.doom9.org/showthread.php?t=174017
