### ISSUE TITLE
There is no function named 'SetFilterMTMode'

### ISSUE THREAD

**Issue by tuanden0** [AviSynth/AviSynthPlus#104]
Dear Sir,

I have a problem with AviSynthPlus-r1576. After install (i chose unistall avisynth normal) and reboot PC. But when I try to to use the script, the AvsP said: There is no function named 'SetFilterMTMode'

There's my script
```
SetFilterMTMode("LSMASHSource",3)
LoadPlugin("E:\Encoder\Tools\LSMASHSource.dll")
LWLibavVideoSource("E:\Download\test zone\test script.mkv")
SetFilterMTMode("",2)
AssumeFPS(24000, 1001)
Toon(0.15)
Deblock(quant=33, bOffset=14)
dfttest()
AAA(Chroma=true)
Spline64Resize(848,480)
aWarpSharp(depth=12,blurlevel=4,thresh=0.3,cm=1)
LimitedSharpenFaster(edgemode=1,strength=200)
deen("a2d",3,6,6)
Dehalo_alpha()
Prefetch(12)
```

**Comment by pinterf** [comment]
That r1576 is an old, non-multithreading version, that does not know about that command.
Currently avisynth plus is still actively developed, please, download the latest version from here
http://forum.doom9.org/showthread.php?p=1784354#post1784354
You can also ask your questions in this forum.

**Comment by tuanden0** [comment]
Thank you, Sir
