### ISSUE TITLE
Jinc r44 version also has a critical memory issue

### ISSUE THREAD

**Issue by cherryfeel** [AviSynth/AviSynthPlus#105]
test enviroment :

source : 24fps Progressive / 1080 Full HD / 16:9
avisynth : avisynth 2.6 MT ( But I didn't use MT command like "setMTmode")
Filter : Jincresize r44
Previewing : Virtualdub 1.10.4
Avisynth Script :
┌────────────────────────────────────────────────────────┐

#   [SOURCE]            #
LWLibavVideoSource("D:\Encoding\[17]\KILL-la-KILL\[Source]\LWI\ep05.lwi", cache=false)
└────────────────────────────────────────────────────────┘

Test -> 1) Resize x2 with Jincresize(36~256) and turn right and turn left for AA in YV16 Color Space.
             2) Resize x1 with Jincresize(36~256) and turn right and turn left for AA in YV16 Color Space.
             3) Resize x2 with Jincresize(36~256) and turn right and turn left for AA in YV12 Color Space.
             4) Resize x1 with Jincresize(36~256) and turn right and turn left for AA in YV12 Color Space.

Result -> 1) msg : "evaluate : Unhandled C++ exception!" from // x2 : YV16 : Jinc256

               2) No Error message // x1 : YV16 : Jinc36&64&144&256

               3) msg : "access violation! at 0x0000964A in JincResize.dll"  or 
                              "evaluate : Unhandled C++ exception!" from // x2 : YV12 : Jinc256

               4) No Error message // x1 : YV12 : Jinc36&64&144&256

**Comment by pinterf** [comment]
Which avisynth+ version are you using?

**Comment by pinterf** [comment]
No response in 4 years, closing
