### ISSUE TITLE
"ImageSource" extremely slow

### ISSUE THREAD

**Issue by FlintEastwood** [AviSynth/AviSynthPlus#107]
Using "ImageSource" is extremely slow in AVS+ . I tried nearly every release (32bit) and it is all the same.
AVS+ = 2,230fps:
[https://abload.de/img/avsp_r2440odzjv.jpg](https://abload.de/img/avsp_r2440odzjv.jpg)
AVS 2.60 = 149,200fps !!! (No MT used):
[https://abload.de/img/avs_v2_60xjxw0.jpg](https://abload.de/img/avs_v2_60xjxw0.jpg)

The script does nothing special. It loads a video-file and adds two images (audio spectrum) below.
I normally would use animate on the images to shift them with the frames, but for finding the bottleneck I did a simple crop to cM and cA. The images are pretty big: 60000x128px. But AVS 2.60 doesn't have a problem with them.

> cin = FFVideoSource("Test.mp4")
> endframe=int((Framerate(cin)*60)-1)
> 
> cM = ImageSource("Test_Mp2.png",fps=Framerate(cin),end=endframe)
> cA = ImageSource("Test_Ac3.png",fps=Framerate(cin),end=endframe)
> 
> cin = Trim(cin,int(05 * 60 * Framerate(cin)),-(endframe+1)).Spline64Resize(1024,576).Crop(0,128,0,-128)
> cM = Crop(cM,0,0,1024,0)
> cA = Crop(cA,0,0,1024,0)
> cA = StackVertical(cM,cA)
> cin = StackVertical(cin,ConvertToYv12(cA))
> 
> return cin

My PC:
i7 870 @ 3,8GHz
Nvidia GTX 1070
12GB RAM DDR3
Win10 Home 64bit
Samsung Evo 850 SSD 500GB

**Comment by pinterf** [comment]
Tested also on AVS 2.6 (2.6.0.5), and experienced the same slowdown. Perhaps the image is not being read once then work from cache, but multiple times.

Instead of 
cM = ImageSource("Test_Mp2.png",fps=Framerate(cin),end=endframe)
cA = ImageSource("Test_Ac3.png",fps=Framerate(cin),end=endframe)

use

cM = ImageSource("Test_Mp2.png",fps=Framerate(cin),end=0).Loop(endframe)
cA = ImageSource("Test_Ac3.png",fps=Framerate(cin),end=0).Loop(endframe)

For me it worked

**Comment by FlintEastwood** [comment]
I get no slowdowns with AVS 2.6 (2.6.0.5) (MT build but MT not used). I can do a full system-restart and starting the script the first time results in 150fps. Following runs result around 151fps.

Your workaround is much better, but still not on AVS 2.60 niveau. I did multiple runs with r2440 and I always get around 137fps.

**Comment by pinterf** [comment]
For more performance, put the YV12 conversions (actually RGB24->YV24->YV12) before the loop, like this:
cM = ImageSource("Test_Mp2.png",fps=Framerate(cin),end=0).ConvertToYv12().Loop(endframe)
cA = ...

Could you check, how it performs now avs 2.6 and avs+? 
(What type of proc and OS are you using?)

**Comment by FlintEastwood** [comment]
I did now three runs with each AVS. 
v2.60 is still a small step faster, sorry. The first two seconds AVSp is pretty slow before it nearly catches up with the speed. You can see it in the MinFPS. But MaxFPS don't hit v2.60 .

Results of each third run:
[https://abload.de/img/avs_v2_60_b7syn.jpg](https://abload.de/img/avs_v2_60_b7syn.jpg)
[https://abload.de/img/avsp_r2440_92sbf.jpg](https://abload.de/img/avsp_r2440_92sbf.jpg)

The optimised script:
> cin = FFVideoSource("Test.mp4")
> endframe=int((Framerate(cin)*60)-1)
> 
> cM = ImageSource("Test_Mp2.png",fps=Framerate(cin),end=0).ConvertToYv12().Loop(endframe)
> cA = ImageSource("Test_Ac3.png",fps=Framerate(cin),end=0).ConvertToYv12().Loop(endframe)
> 
> cin = Trim(cin,int(05 * 60 * Framerate(cin)),-(endframe+1)).Spline64Resize(1024,576).Crop(0,128,0,-128)
> cM = cM.Crop(0,0,1024,0)
> cA = cA.Crop(0,0,1024,0)
> cin = StackVertical(cin,cM,cA)
> 
> return cin

I wish I could have some better news for you. :-/

My PC:
Intel Lynnfield i7 870 @ 3,8GHz
Nvidia GTX 1070
12GB RAM DDR3
Win10 Home 64bit
Samsung Evo 850 SSD 500GB

**Comment by pinterf** [comment]
I'm not arguing which is faster, when I will have a lot of time, maybe I'll investigate it. Anyway, the extremely slow issue is over (I found that Loop() thing in doom9 as an answer to a similar problem with avs 2.6) My last answer was just a suggestion for a further optimization that can benefit both avs branch.

**Comment by FlintEastwood** [comment]
> the extremely slow issue is over

Well, this is true. Thank you for your help. :)
But at the moment I will stay with AVS2.60.
MT is the next thing that will not work right for me in AVSp. But that is maybe, because I'm more familiar with the old MT-syntax in 2.60.
The new syntax maybe needs more optimisation of the used script. 
The example here with

> #SetFilterMTMode("DEFAULT_MT_MODE", 2)
> #SetFilterMTMode("FFVideoSource", 3)
> #SetFilterMTMode("ImageSource", 3)

as the first lines and

> #Prefetch(4)

as last line changes nothing. It behaves like ST. But this is another problem.
