### ISSUE TITLE
Avi not loading after Avisynth+ install

### ISSUE THREAD

**Issue by z400hero** [AviSynth/AviSynthPlus#108]
After installing avisynth+ my avi is loaded in black and white and stretched diagonal.

I reduced the code to:
`AviSource("C:\Demo\demo1.avi")`

Information of the source:
Frame width: 1540
Frame height: 1084
Data rate: 721126kbps
Frame rate:  17frames/second

![afbeelding](https://cloud.githubusercontent.com/assets/28293885/25612221/20a71806-2f2a-11e7-8552-46f478ccde4a.png)

**Comment by qyot27** [comment]
What does it look like when you play it through ffplay or mpv?

**Comment by pinterf** [comment]
No answer, closed
