### ISSUE TITLE
vc redist dll

### ISSUE THREAD

**Issue by anoosi** [AviSynth/AviSynthPlus#109]
hello 
i use avisynth+ with ffmpeg as portable
i just need the dll files of vc redist in ver. AviSynthPlus-MT-r2636

thanks..

**Comment by pinterf** [comment]
The redistributables are always copied from here:
https://www.visualstudio.com/downloads/
Go to the bottom of the page: Microsoft Visual C++ Redistributable for Visual Studio 2017, and choose x86 or x64 version.

**Comment by anoosi** [comment]
@pinterf thanks for reply..
i didn't need installer version of mvc redist .. i only need the dll files..
to work from usb in any pc..

**Comment by pinterf** [comment]
I don't know what's inside their package. It comes with the installer, that's all.
Probably this page helps, I suppose vcruntime140.dll is needed, which I found in c:\Windows\System32\ and c:\Windows\SysWOW64\ folders aftr installation.
https://docs.microsoft.com/hu-hu/cpp/ide/determining-which-dlls-to-redistribute

**Comment by anoosi** [comment]
@pinterf thanks, i will try it

**Comment by anoosi** [comment]
i find it " vcruntime140 , msvcp140 "
close ..
