### ISSUE TITLE
ConvertToRGB with 10 bit source

### ISSUE THREAD

**Issue by 44vince44** [AviSynth/AviSynthPlus#113]
Hello Dear Contributors to this project.

I am using ConvertToRGB with a 10bit source, the result is all green, the conversion is obviously not working as expected.

But if I put before ConvertToRGB the filter ConvertTo8Bit OR ConvertTo16Bit, I get the proper result.

I thought that ConvertToRGB worked with all bit depths, including 10 bits.
Could be a problem? Tested with Avisynth+ v3.4 and also with R2772.

EDIT: If I use ConvertToRGB24 or ConvertToRGB32 or ConvertToRGB48, or ConvertToRGB64, the conversion works fine with all of them, without needing any bit conversion before it. Only ConvertToRGB has this problem. I think either I am missing some point here, or there is a problem with ConvertToRGB. Please excuse me if I am wrong about that. Thanks for all the work!!!

**Comment by qyot27** [comment]
What you want is ConvertToPlanarRGB().  That works with all the bit depths (although whether the receiving application, e.g. VirtualDub2, supports it is another matter).

The longer explanation:

ConvertToRGB is for converting to packed RGB, which was the only RGB type supported by classic AviSynth and older (pre-2016) versions of AviSynth+.  But packed RGB support only exists for 8-bit (RGB24 and RGB32) or 16-bit (RGB48 and RGB64), so trying to convert from anything except those two depths will give unexpected results.  ConvertToRGB24/32/48/64 are convenience functions that combine the conversion to packed RGB with a bit depth conversion to either 8 or 16 bits.

http://avisynth.nl/index.php/Convert
http://avisynth.nl/index.php/Avisynthplus_color_formats

**Comment by 44vince44** [comment]
Thank you very much for your explanation!!
