### ISSUE TITLE
Is422 returns 'False' for a DNxHR file loaded via LSMASHVideoSource()

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [AviSynth/AviSynthPlus#115]
Stumbled upon weird behavior. The function Is422() returns 'False' for DNxHR files that are loaded via LSMASHVideoSource(). But Interleaved() works as expected thou - returns 'True'. PixelFormat() returns YUY2. 
Seems like a bug. Well, unless Is422() is meant to be ( 4:2:2 color AND isPlanar ), not just 4:2:2 ... ? 
Tested on DNxHR files generated by Premiere Pro and FFmpeg, all in .mov container - no differences.

**Comment by qyot27** [comment]
Is422 is for planar formats:
http://avisynth.nl/index.php/Avisynthplus_color_formats

Since FFMS2 decodes it as planar 4:2:2, this would be an L-SMASH-Works issue.
