### ISSUE TITLE
Incorrect encoding

### ISSUE THREAD

**Issue by azlk** [AviSynth/AviSynthPlus#124]
Incorrect encoding in installer?
![2020-02-23_191026](https://user-images.githubusercontent.com/4054635/75115605-288f6200-5671-11ea-8c9b-8820199fd1ce.png)

**Comment by qyot27** [comment]
Already fixed two weeks ago:
https://github.com/AviSynth/AviSynthPlus/issues/121

**Comment by azlk** [comment]
So is AviSynth+ 3.4.0 from here https://github.com/AviSynth/AviSynthPlus/releases ok?
Weird, I just re-downloaded it and nothing changed...

**Comment by AviSynthPlus** [comment]
https://github.com/AviSynth/AviSynthPlus/commit/e890cce92d473e4d0ede7e249cacfffa48c5ccb2
This commit is not included in 3.4.0.
