### ISSUE TITLE
BuildPixelType: chroma default parameter ignores sample_clip

### ISSUE THREAD

**Issue by Kamekameha** [AviSynth/AviSynthPlus#137]
Here,  https://github.com/AviSynth/AviSynthPlus/blob/e17f4f80055009bf45b37e1b6d1790bd1c1a93b2/avs_core/core/parser/script.cpp#L1924

We can see right after the default chroma subsampling is computed from the `sample_clip` (if present) that the parameter gets overridden as if said template clip was not provided.

**Comment by pinterf** [comment]
Thanks, this one appeared on my remove-warnings todo list (do-nothing code, variable as overwritten) but I overlooked its importance. That line was left from v0.01 version of BuildPixelType (no template)

**Comment by Kamekameha** [comment]
Nice, thanks for the fix.
