### ISSUE TITLE
plugins/plugins+/plugins64+

### ISSUE THREAD

**Issue by Selur** [AviSynth/AviSynthPlus#153]
the portable releases change the name of the 'Plugins' folder sometimes it plugins, then it's plugins+ and sometimes the folder for the 64bit version is plugins64+,...
What's up with that?
Will it stick with 'plugins' for the future or will it probably change again?

**Comment by pinterf** [comment]
Probably a mistake. Result of a build traditionally goes into "plugins" folder without "+", but the files have to be put into the plugins+ folder on the user's machine (what the installer is using). We try to use the plugins+ when we are packing together the portable files. Unfortunately we do not always succeed with it.

**Comment by Selur** [comment]
Okay, thanks for clarifying, when using 64bit is it then plugins64+ or should it always be 'plugins+'?

**Comment by pinterf** [comment]
plugins64+ for 64 bit versions

**Comment by Selur** [comment]
Okay thanks :)
