### ISSUE TITLE
Trim produces incorrect number of frames

### ISSUE THREAD

**Issue by sylvainhalle** [AviSynth/AviSynthPlus#161]
## Steps to reproduce

Write this script:

```
ImageSource("any-image.jpg").Trim(0,1499)
```
Open in VirtualDub. Reported clip length is **1001** frames.

## Expected result

Clip length should be **1500** frames. It seems that the `Trim` function produces an incorrect number of frames for large intervals (according to my tests, more than 1000).

## Environment

- Windows 7
- AviSynth+ version 0.1 (r1576, x64)

**Comment by qyot27** [comment]
Okay, two things:

[ImageSource's](http://avisynth.nl/index.php/ImageSource) default clip length is 1001 frames.  [Trim](http://avisynth.nl/index.php/Trim) won't change that.  Use ImageSource's *end=N* parameter to adjust the number of frames returned, where N is the desired end frame.

r1576 is extremely outdated; it was released 6.5 years ago.  [Update to version 3.5.1](https://github.com/AviSynth/AviSynthPlus/releases).

**Comment by sylvainhalle** [comment]
Thanks, that explains everything!

FYI, r1576 is the release we get when downloading from the web page: http://avs-plus.net/

**Comment by qyot27** [comment]
Yeah, that domain doesn't have any automatic updating when we change the gh-pages in the repo, and it was affected by the sporadic hiatuses that occurred early in the project's history.  I don't know if @pinterf can set it up so it as a redirect or a mirror so that we can have avisynth.github.io active, since even if I did make the github-hosted domain active, it wouldn't guarantee people wouldn't still be directed to the outdated one if they find it through Google or something.

**Comment by pylorak** [comment]
> 
> 
> Yeah, that domain doesn't have any automatic updating when we change the gh-pages in the repo, and it was affected by the sporadic hiatuses that occurred early in the project's history. I don't know if @pinterf can set it up so it as a redirect or a mirror so that we can have avisynth.github.io active, since even if I did make the github-hosted domain active, it wouldn't guarantee people wouldn't still be directed to the outdated one if they find it through Google or something.

Sorry, that'd be me, I'm not maintaining contents of that page anymore. I did offer @pinterf last time we talked (2 years ago?) to give him access or transfer it over completely but he wasn't really interested. Offer still stands of course, all you guys need to do is ask.

**Comment by qyot27** [comment]
I had remembered the offer, that was why I wasn't sure if pinterf had taken you up on that.

How complicated is it to push up the contents to avs-plus.net from the gh-pages branch?  As I've never had to handle any sort of website domain admin-ing, that's why I was hesitant to say I'd do so.

**Comment by pylorak** [comment]
Should be easy. But if you're going to use gh-pages as the content anyway then I'll just redirect the domain there. Then updating the website becomes simply pushing a new commit to GitHub.

**Comment by pinterf** [comment]
Yep, I was offered indeed, but at that time I was reluctant to do anything serious about the project. And since I have zero experience in web-related maintenance, other that writing webservices I missed the opportunity. (I have to look into what gh-pages really is)

**Comment by pylorak** [comment]
I pointed the domain (both with and without "www") to the gh-pages branch, so the website is now served from the contents of the repository. I enabled https and slightly updated the feature list on the index page. The rest is up to you :)

**Comment by qyot27** [comment]
Thanks!  This will also help give a more 'press formal' reference for anybody (*a-hmm* Wikipedia) asking for a reliable source that AviSynth+ runs on more than just Windows or x86(-64).
