### ISSUE TITLE
wrong file published ?

### ISSUE THREAD

**Issue by ilko-k** [AviSynth/AviSynthPlus#164]
the core .dll file found in "AviSynthPlus_3.5.1_20200402_filesonly.7z" indicates that the version is 3.5.0, not 3.5.1.

**Comment by qyot27** [comment]
It indicates the version is '3.5', without the bugfix version, and MSVC adds extra zeroes.  That's all. The bugfix version was added to the .rc and the output of Version() in mid-April.

But one look at the revision number it reported in the DLL resources would have confirmed it was 3.5.1.

**Comment by ilko-k** [comment]
![image](https://user-images.githubusercontent.com/5411848/82162005-8fec3500-98a1-11ea-9b51-32fd2424d910.png)

where ?
