### ISSUE TITLE
GeneralConvolution issues

### ISSUE THREAD

**Issue by realfinder** [AviSynth/AviSynthPlus#170]
the output of GeneralConvolution seems different from AviSynth 2.6
using
ConvertTorgb32
GeneralConvolution(Matrix="-1 2 -1 2 0 2 -1 2 -1")

with avs+ it look more blurly

also it's crash in avspmod when press f5 for 2 times or more if there are some space between  -1 and 2 or 2 and -1

**Comment by pinterf** [comment]
You are right, negative coefficients were parsed and rounded incorrectly, regression since r2772
Crash: which test or non-test version you are using?

**Comment by realfinder** [comment]
> 
> 
> Crash: which test or non-test version you are using?

I tested with r3106

**Comment by realfinder** [comment]
ok, it's not the space

https://github.com/realfinder/AVS-Stuff/blob/85d089704c1b4c2ae0a39d586b3dec2fcc70b215/avs%202.5%20and%20up/AdvancedDenoising.avsi#L484

```
colorbars()
converttoyv12
sGConvolution(Matrix="-1 2 -1 2 0 2 -1 2 -1",chroma=true)
```

**Comment by pinterf** [comment]
Thanks, reproduced. crash when chroma=true and 420 or 422 formats

**Comment by pinterf** [comment]
Thanks for the reports, pls check test build 8
https://drive.google.com/file/d/1a5VlaM3ZVjq9KwBk5piamswc_sV5bY_j/view?usp=sharing

**Comment by realfinder** [comment]
that fix it, thanks
