### ISSUE TITLE
avs2yuv throw error: failed to load avisynth.dll

### ISSUE THREAD

**Issue by kimown** [AviSynth/AviSynthPlus#179]
Here is my steps:
1. download [AviSynthPlus_3.6.1_20200619.exe](https://github.com/AviSynth/AviSynthPlus/releases/tag/v3.6.1), Custom Installation, only select `AviSynthb + (x64)`
![image](https://user-images.githubusercontent.com/7932380/87378086-a7a11a80-c5bf-11ea-852e-36f5a69eb812.png)

2. download [ avs2yuv](https://github.com/MasterNobody/avs2yuv/releases/tag/v0.24bm6), the zip package contains `avs2yuv.exe` and `avs2yuv64.exe`
3. run `avs2yuv.exe Version.avs -o version.y4m && ffmpeg -y -i version.y4m version.y4m.mp4` or `avs2yuv64.exe Version.avs -o version.y4m && ffmpeg -y -i version.y4m version.y4m.mp4` throw  error: failed to load avisynth.dll
4. but when I select `AviSynthb + (x86)`, the error was gone

**Comment by qyot27** [comment]
You probably need to install the x64 vcredist for 2015-2019.  Because both 0.24bm6 linked to and the [updated 0.29](https://github.com/DJATOM/avs2yuv) work here.

Or just eschew avs2yuv entirely and open the script using FFmpeg/ffplay/mpv directly?

**Comment by kimown** [comment]
> You probably need to install the x64 vcredist for 2015-2019. Because both 0.24bm6 linked to and the [updated 0.29](https://github.com/DJATOM/avs2yuv) work here.
> 
> Or just eschew avs2yuv entirely and open the script using FFmpeg/ffplay/mpv directly?

Thanks for your reply,  I downloaded and installed [vc_redist.x64.exe](https://support.microsoft.com/en-sg/help/2977003/the-latest-supported-visual-c-downloads),  ` avs2yuv64.exe Version.avs -o version.y4m && ffmpeg -y -i version.y4m version.y4m.mp4`, this command works, many thanks for your help
