### ISSUE TITLE
wine64 support in linux

### ISSUE THREAD

**Issue by kimown** [AviSynth/AviSynthPlus#181]
I can install [avisynth2](http://avisynth.nl/index.php/SourceForge) in wine32 and it works well, but I can't install AviSynthPlus, it throw error `not support on this system` like screenshot below, does AviSynthPlus support wine64
![image](https://user-images.githubusercontent.com/7932380/88057098-284db100-cb94-11ea-995c-977cb9c9fab5.png)

**Comment by qyot27** [comment]
It's the InnoSetup installer; a cursory Googling isn't bringing up anything about that conflicting with Wine64, but that doesn't mean there isn't a problem there.  But as long as there's an installation of AviSynth already present in Wine, you can just copy the new Plus .dlls over the old ones.  If you absolutely need to run the installer to migrate your plugin directories from 2.6 to Plus, go back to the installer for r1576/0.1 - that one should properly set up the registry entries for the additional Plus-specific default plugin directories.  And then use the filesonly package to copy over the .dlls.

Also, make sure that you've installed the 2015-2019 vcredist, unless Wine has advanced enough that that's not needed.

**Comment by kimown** [comment]
> It's the InnoSetup installer; a cursory Googling isn't bringing up anything about that conflicting with Wine64, but that doesn't mean there isn't a problem there. But as long as there's an installation of AviSynth already present in Wine, you can just copy the new Plus .dlls over the old ones. If you absolutely need to run the installer to migrate your plugin directories from 2.6 to Plus, go back to the installer for r1576/0.1 - that one should properly set up the registry entries for the additional Plus-specific default plugin directories. And then use the filesonly package to copy over the .dlls.
> 
> Also, make sure that you've installed the 2015-2019 vcredist, unless Wine has advanced enough that that's not needed.

https://github.com/AviSynth/AviSynthPlus/releases/tag/Rel-r1576

does `r1576/0.1` means this version, I will have a try.
