### ISSUE TITLE
None of Windows installers start on Server 2016

### ISSUE THREAD

**Issue by mxhaj79** [AviSynth/AviSynthPlus#183]
Irrespective of the compatibility settings, I am unable to run installer 3.50 or newer on Server 2016. Is this intended behavior? I have tried latest versions i.e., AviSynthPlus_3.6.1_20200619_vcredist.exe and AviSynthPlus_3.6.1_20200619.exe with the same null effect. I am using AviSynthPlus in combination with StaxRip and it is critical for its proper operation.

**Comment by qyot27** [comment]
Check your UAC settings, that's the first thing I can think of.  It launches as expected on normal Windows 10 Pro 2004, so I'd assume it's down to OS configuration differences between Win10 and Server 2016.

**Comment by mxhaj79** [comment]
It is executed under Admin account, and the same behavior persists when running it as Admin as well. The very same file works correctly under Windows 10, no issues there, but does not even budge under Server 2016.

**Comment by pylorak** [comment]
I assume you already unblocked the installer as internet content?
https://social.technet.microsoft.com/Forums/office/en-US/badb7948-fa12-4670-8144-8b15ccd78af5/click-exe-installer-and-nothing-happens?forum=ws2016

**Comment by mxhaj79** [comment]
I checked that as well. There was no unblock button. Thanks for sharing!

What seems to have helped finally is downloading the file on a different machine, running it (at least to the point of having the initial dialog display) and then copying the file over to Server 2016 machine. I do not understand what it changed, since file hash and properties look exactly the same before and after, but now the file starts correctly. 

Really confusing. 

Thanks for helping out !

**Comment by artenaki** [comment]
Internet zone information is stored in NTFS file streams, I guess. If you copied file to another computer via exFAT, FAT32, Ext4 file systems, Internet zone information may have been removed.
