### ISSUE TITLE
High bitdepth + Blur causes a green bar

### ISSUE THREAD

**Issue by Boulder08** [AviSynth/AviSynthPlus#184]
As discussed at the doom9 forum, using Blur in high bitdepth sometimes causes a strange bar appear in the image.

This can be used to reproduce the issue with AVX/AVX2 capable CPUs:
Colorbars(720,576,"YV12")
ConvertBits(16)
Blur(0.65)

I've found out that also cropping 220 pixels off both left and right side of a 1080p source will cause it in the same circumstances.
I'm using a Ryzen 3900X system with Avisynth+ 3.6.2-test1 installed.

**Comment by pinterf** [comment]
Thanks for the report.
Fixed in https://github.com/AviSynth/AviSynthPlus/commit/b41c55b34cab0c3a3aa91562f225de90f2352b32
