### ISSUE TITLE
issues in how last avs+ deal with the parameters

### ISSUE THREAD

**Issue by realfinder** [AviSynth/AviSynthPlus#186]
Hi,

seems there are bug or something for many cases like https://forum.doom9.org/showpost.php?p=1920166&postcount=622 and https://forum.doom9.org/showpost.php?p=1918913&postcount=5 and https://forum.doom9.org/showthread.php?p=1920018#post1920018 , AviSynth+ 3.5.X was fine with them

thanks

**Comment by pinterf** [comment]
Looking into it

**Comment by pinterf** [comment]
Fixed in commit https://github.com/AviSynth/AviSynthPlus/commit/2d77f6d92662bc4e7ee5e9212676a3745bd5089e

**Comment by pinterf** [comment]
Hm. But it made problems with Stackvertical which has multiple clip inputs and if tried first with implicite "last", it will use StackVertical(last, clip1,clip2) for a StackVertical(clip1,clip2)

**Comment by realfinder** [comment]
gWriteFileIf case still not fixed

**Comment by pinterf** [comment]
Found something, need some more time. The array of strings parameters for WriteFileIf 
`.WriteFileIf(scFile, "boolSC==true", "current_frame")`
was not recognized against the "s+" parameter specifier.
(The "boolSC==true" and the "current_frame" parameters are moved into an array in the calling situation above)

**Comment by pinterf** [comment]
Could you please check this build (common with the current win10 long filename support test):
https://drive.google.com/file/d/1CTU9DlMg_pyMwAzqMN9crSzt7eBFzWxk/view?usp=sharing

**Comment by realfinder** [comment]
I did a test with https://forum.doom9.org/showthread.php?p=1918893#post1918893 and it's now work fine, thanks

**Comment by pinterf** [comment]
Fixed in https://github.com/AviSynth/AviSynthPlus/commit/ac90e98e0e51f7bcd6b321c48fab0a7db1e69b9e

**Comment by realfinder** [comment]
so I will close this for now
