### ISSUE TITLE
Long path support in Windows 10

### ISSUE THREAD

**Issue by stax76** [AviSynth/AviSynthPlus#187]
avs files with long paths cannot be imported, GetShortPathName can be used as workaround, it would be nice if it would be supported natively like in VapourSynth.

https://github.com/staxrip/staxrip/blob/master/FrameServer/AviSynthServer.cpp#L78

**Comment by qyot27** [comment]
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
https://docs.microsoft.com/en-us/cpp/c-runtime-library/path-field-limits?view=vs-2019

We already use `MAX_PATH`.  Have for years:
https://github.com/AviSynth/AviSynthPlus/search?q=MAX_PATH&unscoped_q=MAX_PATH
https://github.com/AviSynth/AviSynthPlus/search?q=_MAX_PATH&unscoped_q=_MAX_PATH

**Comment by stax76** [comment]
Isn't MAX_PATH always 260? Windows 10 supports paths that are longer than 260 character and I believe avisynth should accept such long paths without prefixing it with `\\?\` and without converting it to short paths, hardly any tools support that, of all tools used by staxrip it works only with MediaInfo, VapourSynth and qaac, for all other tools staxrip converts the long path to a short path.

**Comment by pinterf** [comment]
Yep, MAX_PATH is now a limiting factor, win10 allows longer than that.

**Comment by pinterf** [comment]
Please try this test build (7z download)
https://drive.google.com/file/d/1CTU9DlMg_pyMwAzqMN9crSzt7eBFzWxk/view

**Comment by stax76** [comment]
Thanks for the fast support pinterf, unfortunately I cannot try it until Saturday.

**Comment by stax76** [comment]
@pinterf 

I tried to download it with Chrome and Edge but Google Drive blocks the download with an error that tells that the file has a virus.

**Comment by stax76** [comment]
I found a working download link at doom9 and confirm that longs paths are working, thank you!
