### ISSUE TITLE
TV range with float

### ISSUE THREAD

**Issue by TbtBI** [AviSynth/AviSynthPlus#189]
Hi,
This
```
BlankClip(pixel_type="rgbps") 
Converttoyuv420()
```
gives 16 / 255 values. If I understand correctly the answer from [here](https://github.com/sekrit-twc/zimg/issues/134#issuecomment-687845490) the expected values should be 0. Does AviSynth+ have wrong behavior for such situation?

**Comment by pinterf** [comment]
Probably convertToYUV420 needs a full range option parameter ("PC.xxx"), it is not automatic for float.

Note that (for historical reasons) there is no explicite internal standard in avs+ whether 32 bit float YUV is treated as full-range (Y:0..1 Chroma -0.5..0.5) or limited (the original range divided by 255 e.g. Y:16/255.0-235/255.0, chroma: (Chroma-128)/255.0. 

Early avs+ versions even did not treat chroma in +/-0.5 range but simply U/255 and V/255, changing that was a nice big project for me some years ago.

Ideally 32 bit float YUV should have only one interpretation: limited or full scale 8-16 bits -> 32 bit float: Y: 0-1.0 and U,V:-0.5..0.5
Also note that in Avisynth+ the system does not know about the limited/full-ness of a clip unlike VS where the frame properties are marking it properly throughout the whole system.

**Comment by realfinder** [comment]
isn't frame properties also addd in avs+ months ago?

**Comment by pinterf** [comment]
Passing, setting and reading frame properties are now supported of course.
But I think no plugin is using that at the moment so no property is set.
First, a source filter should to write specific meta-data of the source into frame properties, resizers and colorspace conversions then can alter and act upon them.
E.g. z_ConvertFormat would recognize and change the actual color matrix and take it into consideration automatically like the VapourSynth version of the zimg resizer does.
VapourSynth has predefined keywords and they are used consistently across their ecosystem. _ChromaLocation, _Matrix, _Primaries, _Transfer, _DurationDen, _DurationNum etc...

**Comment by TbtBI** [comment]
> Note that (for historical reasons) there is no explicite internal standard in avs+ whether 32 bit float YUV is treated as full-range (Y:0..1 Chroma -0.5..0.5) or limited (the original range divided by 255 e.g. Y:16/255.0-235/255.0, chroma: (Chroma-128)/255.0.

> Ideally 32 bit float YUV should have only one interpretation: limited or full scale 8-16 bits -> 32 bit float: Y: 0-1.0 and U,V:-0.5..0.5

Then why not set such standard? You're the main developer so mostly it depends on you. Since there is no float support for AviSynth 2.5/2.6 there shouldn't be legacy concerns, right?

> VapourSynth has predefined keywords and they are used consistently across their ecosystem. _ChromaLocation, _Matrix, _Primaries, _Transfer, _DurationDen, _DurationNum etc...

Can we have also such predefined keywords? Currently the source filter can set _ChromaLocation property but some other filter can read/set ChromaLocation_ for example. It's not convenient to search what property name every plugin set.

**Comment by realfinder** [comment]
well, at least there are some by asd https://github.com/Asd-g/yadifmod2/commit/9b16919af5d37759044be6e594b747879d9eb014

**Comment by TbtBI** [comment]
Here there are set properties https://github.com/Asd-g/RawSource_2.6x/commit/13a0fd8119bc74f92b126bda6653af08a4ccb7d3
Also here https://github.com/Asd-g/AviSynthPlus-Scripts/blob/master/ComparisonGen.avsi#L97

**Comment by pinterf** [comment]
> Then why not set such standard? You're the main developer so mostly it depends on you. Since there is no float support for AviSynth 2.5/2.6 there shouldn't be legacy concerns, right?

It mostly depend on time, I no longer can do hobby programming 60-100 hours per month. Rather divide this number by 10 and imagine what it is enough for. Virtually nothing.

**Comment by TbtBI** [comment]
Ok.

Regards.

**Comment by realfinder** [comment]
isn't matrix parameter already there?
```
BlankClip(pixel_type="rgbps") 
Converttoyuv420(Matrix="PC.601") #or PC.709
ConvertBits(8)
```
this work
added ConvertBits(8) since avspmod has bug or something with HBD and show y as 16.

anyway there are z_ConvertFormat if anyone want the VS way

**Comment by realfinder** [comment]
I think convertToYUV4XX and convertToY need Transfer Characteristics and Color Primaries parameters instead of that

**Comment by realfinder** [comment]
there are no PC.2020 ? http://avisynth.nl/index.php/Convert#Matrix

**Comment by pinterf** [comment]
> 
> 
> well, at least there are some by asd [Asd-g/yadifmod2@9b16919](https://github.com/Asd-g/yadifmod2/commit/9b16919af5d37759044be6e594b747879d9eb014)

This one "only" ensures that frame props are not lost during copying (I have implemented this in my lately updated filters and avisynth core filters)

**Comment by pinterf** [comment]
> 
> 
> Here there are set properties [Asd-g/RawSource_2.6x@13a0fd8](https://github.com/Asd-g/RawSource_2.6x/commit/13a0fd8119bc74f92b126bda6653af08a4ccb7d3)
> Here there is reading of properties https://github.com/Asd-g/AviSynthPlus-Scripts/blob/master/ComparisonGen.avsi#L97

Yep, this one is really the very first usage of Avisynth+ frame properties! Big cheers to Asd-g!

**Comment by pinterf** [comment]
> anyway there are z_ConvertFormat if anyone want the VS way (with frame properties since r1f 2020/08/25)
Looking at the source, it is not using frame properties at all, like VS does.
It only implements the basic "frame properties are copyied and not lost during NewVideoFrame" technique.

**Comment by TbtBI** [comment]
Since the discussion moved from full/tv range to frame properties I have two questions unrelated to both topics.

Does avs+ if..else have additional overhead compared to ternary? For example:
```
if (show){
clip.do_something
}

# show ? clip.do_something : NOP()
```
```
if (show){
var = x
}
else{
var = y
}

# var = show ? x : y
```
#######
It seems once you initialize array you cannot change the elements.
```
var = [1, 2]
Subtitle(String(var[x])) # Subtitle(String(ArrayGet(var, x)))
```
You can read the elements but you cannot overwrite them. Or am I missing something?
