### ISSUE TITLE
GenericConvolution wrong output for non-float bit depth

### ISSUE THREAD

**Issue by TbtBI** [AviSynth/AviSynthPlus#196]
Hi,
Here an example how the issue could be reproduced:
```
yv12 input
a=ConvertBits(32).GeneralConvolution(matrix="1, 1, 1, 1, 1, 1, 1, 1, 1", chroma=false, alpha=false).ConvertBits(8) # correct output
#a=GeneralConvolution(matrix="1, 1, 1, 1, 1, 1, 1, 1, 1", chroma=false, alpha=false) # wrong output
#mt_mappedblur(last, last, "1, 1, 1, 1, 1, 1, 1, 1, 1", mode="dump") # little difference compared to mt_convolution
mt_convolution("1 1 1", "1 1 1")
Compare(a, "y")
```

**Comment by pinterf** [comment]
Good catch! There was a missing rounder in the integer GeneralConvolution calculation.

**Comment by pinterf** [comment]
On the other hand, this old comment says:
"    // Truncate instead of round - keep in the spirit of the original code"
I'm not convinced that it should be kept.

**Comment by TbtBI** [comment]
Probably, yes. That comment is [17 years old](https://github.com/AviSynth/AviSynthPlus/commit/b895c0ff612e05cec62c2e3af5ca00a033be332b#diff-11281d367d9dd76c647520025f9a40f7e059a695b6b16be210e07cd4b9a350ea). Avs+ supports any bit depth and color format so it's better to get more expected result imo.

**Comment by pinterf** [comment]
New build, check please
https://drive.google.com/uc?export=download&id=1Ow2g4H16B3PvXWiD9VGXkJSQk7mBaxb5

**Comment by TbtBI** [comment]
Only 16-bit is different now.
```
yv12 input
ConvertBits(16)
a=GeneralConvolution(matrix="1, 1, 1, 1, 1, 1, 1, 1, 1", chroma=false, alpha=false) # different output
mt_convolution("1 1 1", "1 1 1")
Compare(a, "y")
```
But the following example gives identical output.
```
yv12 input
ConvertBits(16)
a=GeneralConvolution(matrix="1, 1, 1, 1, 1, 1, 1, 1, 1", chroma=false, alpha=false).ConvertBits(8) # different output
mt_convolution("1 1 1", "1 1 1").ConvertBits(8)
Compare(a, "y")
```

**Comment by pinterf** [comment]
There is still a minor algorithmic difference between mt_convolution and GeneralConvolution in how they do the division.
In this version I cannot make them more similar to each other, applying the rounding internally helped a lot.

**Comment by TbtBI** [comment]
8/10/12/14/32-bit are identical only 16-bit is not. The difference is very small but I was surprised that the other int high bit depths (10/12/14) are identical.

Thanks for the update.

Btw is there a chance to add parameter saturation like VS convolution and mt_convolution saturate? That way saturation could be disabled if necessary.

**Comment by pinterf** [comment]
Do they work the same way? VS convolution and mt_conv? (in order to which one to look into it)

**Comment by TbtBI** [comment]
Both std.Convolution(saturate=0) and mt_convolution(saturate=false) have visible identical outputs.

Btw std.Convolution(video, matrix=[1, 1, 1, 1, 1, 1, 1, 1, 1], saturate=1, planes=0) and GeneralConvolution(matrix="1, 1, 1, 1, 1, 1, 1, 1, 1", chroma=false, alpha=false)/mt_convolution("1 1 1", "1 1 1") aren't identical - https://imgbox.com/g/vKrIMu17vS (1st VS, 2nd AVS+, 3rd source). Check the top line.

**Comment by TbtBI** [comment]
Closing this issue since the problem from the title is fixed.
Thanks again for the fast fix.
