### ISSUE TITLE
RST documentation

### ISSUE THREAD

**Issue by qyot27** [AviSynth/AviSynthPlus#20]
I'm currently in the process of moving the documentation to reStructuredText.  The FilterSDK stuff is in pretty rough shape content-wise (<i>really</i> rough, more than a little of it has to do with inline asm), but I started with it because the rest of the documentation is mostly language-specific versions of the same basic docs and probably won't need nearly as much critiquing.  I'm getting started on the English docs next.

This way, the docs are easier to maintain, and we can use rst2html/rst2pdf/rst2man to convert them into more traditional documentation later (and on-demand, but that'd require buildsystem integration with docutils, which is far more of interest on Linux/OSX than it is on Windows).

The HTML docs get moved to the htm/ subdirectory while the RST docs get proofed, and once everything's been worked out, the directory can be safely deleted.  The .css and image elements remain because the RST docs can use them, either directly (images) or with the conversion software (.css).

The upside, of course, is that they're also now viewable directly on Github:
https://github.com/qyot27/avisynth/tree/rstification/distrib/FilterSDK

But how should I handle the pull request(s)?  Should they be issued for each language as each directory is completed, or should I wait until all of them have been converted?  I could issue one for FilterSDK right now, but I'd prefer if the irrelevant stuff is identified and removed/edited before I do.

**Comment by pylorak** [comment]
English RST docs have been merged in.
