### ISSUE TITLE
propSet/propDelete... doesn't pass already created runtime variables

### ISSUE THREAD

**Issue by TbtBI** [AviSynth/AviSynthPlus#200]
Hi,
Example: 
```
yv input
FrameEvaluate("""a=YPlaneMax()""")
#ScriptClip("""propset("prope_", 4)""") # The last line returns "I don't know what 'a' means".
ScriptClip("""Subtitle(String(a))""")
```

**Comment by pinterf** [comment]
I'm always getting "don't know what 'a' means" with or without the propSet line.

You can try this
```
ColorBars().ConvertToYV12()
ScriptClip("""propset("prope_", YPlaneMax())""")
ScriptClip("""Subtitle(String(propGetInt("prope_")))""")

```

**Comment by TbtBI** [comment]
```
ColorBars(pixel_type="yv12")
FrameEvaluate("""a=YPlaneMax()""")
#ScriptClip("""propset("prope_", 4)""") # The last line returns "I don't know what 'a' means".
ScriptClip("""Subtitle(String(a))""")
```
Above result - https://images2.imgbox.com/01/92/xEwUTEVc_o.png

```
ColorBars(pixel_type="yv12")
FrameEvaluate("""a=YPlaneMax()""")
ScriptClip("""propset("prope_", 4)""") # The last line returns "I don't know what 'a' means".
ScriptClip("""Subtitle(String(a))""")
```
Above result - https://images2.imgbox.com/29/4d/NkAQ4VcC_o.png

**Comment by pinterf** [comment]
I found no avisynth version (including the original classic 2.6) that would work with your top sample.
Strangely, the error is displayed only for the first frame! When I step forward in vdub2, the value of the variable is there.

**Comment by pinterf** [comment]
Side note: setting variables in such a way is not mt friendly
I know, this problem is not multithread related, but still, I suspect timing or cacheing conditions between our success/no success experience.

**Comment by TbtBI** [comment]
> Side note: setting variables in such a way is not mt friendly

In what way? ScriptClip("""a=a ... ?

**Comment by pinterf** [comment]
No. Setting it runtime and use it later, runtime as well.

**Comment by TbtBI** [comment]
Is it the same (non-mt friendly) with FFPICT_TYPE (ffms2) too?
```
ScriptClip("""FFPICT_TYPE=FFPICT_TYPE 
propset("prope_", 4)""", after_frame=true)
```

**Comment by pinterf** [comment]
I had to think it over.
Could you please test this build:
https://drive.google.com/uc?export=download&id=1YpPWasnhj_HulTB23CdMkGMaqEb0YyYb

**Comment by TbtBI** [comment]
It's ok, thanks.

> edit: and you don't have to use propSet within ScriptClip, you can use propSet and assign a fix value to a property anywhere. Only the propGet family members need to be runtime functions. Of course a runtime property will override the script level one.

Thanks for the info.
