### ISSUE TITLE
Scriptclip issue

### ISSUE THREAD

**Issue by crabshank** [AviSynth/AviSynthPlus#209]
I had a script set up which used Scriptclip, but in any version after 3.5.1 the script breaks; there's also an issue with Scriptclip not working with Prefetch. I am using a 3770k CPU with the x64 version of Avisynth.

**Comment by pinterf** [comment]
Avisynth 3.7 I guess.
Please, specify "breaks", provide a minimum script you still encounter with the "break" and a bit more about the Prefetch problem.

**Comment by crabshank** [comment]
### Using one of my own functions, and it works with 3.5.1 but no later versions

cd="C:\Program Files\AvsPmod"   
      
Loadplugin(cd+"\plugins\MPEG2DecPlus64.dll")	            

function framesAroundTop(clip clip, int base){
s=70
a=StackHorizontal(clip.trim(base-4,base-4).Subtitle(String(base-4),size = s),StackHorizontal(clip.trim(base-3,base-3).Subtitle(String(base-3),size = s),StackHorizontal(clip.trim(base-2,base-2).Subtitle(String(base-2),size = s),StackHorizontal(clip.trim(base-1,base-1).Subtitle(String(base-1),size = s),clip.trim(base,base).Subtitle(String(base),text_color=color_lime,size = s)))))
b=StackHorizontal(clip.trim(base+1,base+1).Subtitle(String(base+1),size = s),StackHorizontal(clip.trim(base+2,base+2).Subtitle(String(base+2),size = s),StackHorizontal(clip.trim(base+3,base+3).Subtitle(String(base+3),size = s),StackHorizontal(clip.trim(base+4,base+4).Subtitle(String(base+4),size = s),clip.trim(base+5,base+5).Subtitle(String(base+5),size = s)))))
c=StackHorizontal(clip.trim(base+6,base+6).Subtitle(String(base+6),size = s),StackHorizontal(clip.trim(base+7,base+7).Subtitle(String(base+7),size = s),StackHorizontal(clip.trim(base+8,base+8).Subtitle(String(base+8),size = s),StackHorizontal(clip.trim(base+9,base+9).Subtitle(String(base+9),size = s),clip.trim(base+10,base+10).Subtitle(String(base+10),size = s)))))
d=StackHorizontal(clip.trim(base+11,base+11).Subtitle(String(base+11),size = s),StackHorizontal(clip.trim(base+12,base+12).Subtitle(String(base+12),size = s),StackHorizontal(clip.trim(base+13,base+13).Subtitle(String(base+13),size = s),StackHorizontal(clip.trim(base+14,base+14).Subtitle(String(base+14),size = s),clip.trim(base+15,base+15).Subtitle(String(base+15),size = s)))))
e=StackHorizontal(clip.trim(base+16,base+16).Subtitle(String(base+16),size = s),StackHorizontal(clip.trim(base+17,base+17).Subtitle(String(base+17),size = s),StackHorizontal(clip.trim(base+18,base+18).Subtitle(String(base+18),size = s),StackHorizontal(clip.trim(base+19,base+19).Subtitle(String(base+19),size = s),clip.trim(base+20,base+20).Subtitle(String(base+20),size = s)))))
return StackVertical(a,StackVertical(b,StackVertical(c,StackVertical(d,e))))
}

 Input = MPEG2Source("....d2v", moderate_h=0,moderate_v=0,cpu=0,iPP=false,iCC=false,idct =3,cpu2 = "oooooo").AssumeFPS(24000.0/1001.0)
 
 Input=Input.ConvertToRGB32(matrix="Rec601", interlaced=false)

Input

SSS="""
PointResize(framesAroundTop(Input,current_frame),720,480)
"""

i0=Scriptclip(SSS,After_Frame=True)
Input
SSS2="""
p=(current_frame)*pow(framecount(Input)-1,-1)*100
q=ceil(0.0625*((framecount(Input))-(current_frame+1)))
 Subtitle(String(q,"%.0f")+String(" - ")+String(p,"%.2f")+String("% - ")+String(current_frame,"%.0f")) 
"""

i1=Scriptclip(SSS2,After_Frame=True)

StackHorizontal(i0,i1)
SetMemoryMax(3072)
Prefetch(6)

**Comment by pinterf** [comment]
The github comment engine needs using "insert code" icon, or else special characters are not shown.
E.g. see the end of this line, there is nothing between ) and 100
p=(current_frame)*pow(framecount(Input)-1,-1)100

**Comment by crabshank** [comment]
> The github comment engine needs using "insert code" icon, or else special characters are not shown.
> E.g. see the end of this line, there is nothing between ) and 100
> p=(current_frame)*pow(framecount(Input)-1,-1)100

Apologies, fixed now.

**Comment by pinterf** [comment]
O.K. much better.
Scriptclip: Function did not return a videoclip with the same height as the source clip 

And there is a displayed subtitle: 301 - 0.0% - 0

**Comment by crabshank** [comment]
It worked on the first frame for me, then stopped working a few frames in.

**Comment by pinterf** [comment]
I'm trying in virtualdub2, so far without Prefetch

**Comment by crabshank** [comment]
I use AvsPmod 2.6.4.3 x64

**Comment by pinterf** [comment]
is your original clip dimension is 720,480?

**Comment by crabshank** [comment]
Yes

**Comment by pinterf** [comment]
O.K.
In MT environment you cannot use the external Input variable inside ScriptClip.
Different threads will use different instance of Input, one thread is setting Input, the other one processes the ScriptClip and does not know about the "Input" created in another thread. Even the thread is seeing "Input" it is not known whether it sees the right one of the many "Input"s of different threads.

Now I invoked ScriptClips with the Input.Scriptclip syntax and was using "last" inside ScriptClip.

 
```
Input=Input.ConvertToRGB32(matrix="Rec601", interlaced=false)

SSS="""
PointResize(framesAroundTop(current_frame),720,480)
"""

i0=Input.Scriptclip(SSS,After_Frame=True)

SSS2="""
p=(current_frame)*pow(framecount(last)-1,-1)*100
q=ceil(0.0625*((framecount(last))-(current_frame+1)))
 Subtitle(String(q,"%.0f")+String(" - ")+String(p,"%.2f")+String("% - ")+String(current_frame,"%.0f")) 
"""

i1=Input.Scriptclip(SSS2,After_Frame=True)

StackHorizontal(i0,i1)
SetMemoryMax(3072)
Prefetch(6)

```

**Comment by crabshank** [comment]
Thank you very much, this works.

**Comment by pinterf** [comment]
Or use the new syntax (uncommented the old one, below is the other method: function objects)
```
#i0=Input.Scriptclip(SSS,After_Frame=True)
i0=Input.Scriptclip(function[](clip c) { PointResize(framesAroundTop(current_frame),720,480) }, After_Frame=True)
```
and

```
#i1=Input.Scriptclip(SSS2,After_Frame=True)
i1=Input.Scriptclip(function[](clip c) { p=(current_frame)*pow(framecount(last)-1,-1)*100 \
q=ceil(0.0625*((framecount(last))-(current_frame+1))) \
 Subtitle(String(q,"%.0f")+String(" - ")+String(p,"%.2f")+String("% - ")+String(current_frame,"%.0f")) \
}, After_Frame=True)

```

**Comment by pinterf** [comment]
This latter one (function objects) I think does not run on 3.5.x.

**Comment by crabshank** [comment]
I have upgraded now; thanks so much for your help.
