### ISSUE TITLE
Access violation in module ntdll.dll when loading YATTA

### ISSUE THREAD

**Issue by mirkosp** [AviSynth/AviSynthPlus#218]
Hi there! I'm terrible with error reports and maybe it's not exactly in issue in avs+ itself, but here goes.

Starting AVS+ version 3.6.0 I get the following error message when trying to load YATTA:
[https://cdn.discordapp.com/attachments/423197792077348866/855165265402396672/unknown.png](https://cdn.discordapp.com/attachments/423197792077348866/855165265402396672/unknown.png)
which of course doesn't work as intended afterwards.

I've confirmed this issue is still there with 3.6.1 and 3.7.0 as well.

Reverting to AVS+ 3.5.1 makes YATTA load and work just fine.

This is the stack with symbols from visual studio which a friend of mine made me do when I tried some debugging to understand where the issue might lie:
[https://cdn.discordapp.com/attachments/423197792077348866/855163877356339250/unknown.png](https://cdn.discordapp.com/attachments/423197792077348866/855163877356339250/unknown.png)

As I am not well versed in programming at all, I do not know if this stems from some regression in avs+ itself, or if the problem's somewhere within YATTA.
Any help would be appreciated!

EDIT: upon further inspection, this might be related to the  VSpritf change mentioned in the 3.6.0 changelog. I assume this then falls within updating yatta's asif code.

**Comment by mirh** [comment]
The VSprintf change was already there in 3.5.1. 
This must be that in 3.6.1 they still didn't fix the majority of the C api regressions.
