### ISSUE TITLE
Make this repo not a fork from jeeb/avisynth

### ISSUE THREAD

**Issue by TimothyGu** [AviSynth/AviSynthPlus#22]
Being a fork disallows code search within this repo.

**Comment by qyot27** [comment]
>Although this could be because I forked while the repo name was still 'avisynth' and haven't yet changed the repo name to match upstream.

This is exactly the reason it kept screwing up.  I finally renamed mine to AviSynthPlus to match, and it no longer tries to open the PR against JEEB's repo.

**Comment by pylorak** [comment]
We'll think about what to do if JEEB stops updating. Until then any other action is just a waste of resources.
