### ISSUE TITLE
convert array to arguments, and others issues about array

### ISSUE THREAD

**Issue by realfinder** [AviSynth/AviSynthPlus#226]
as said here https://forum.doom9.org/showpost.php?p=1949717&postcount=1258

<html><body>
in <a href="https://github.com/AviSynth/AviSynthPlus/tree/master/distrib/Readme" target="_blank">this</a> read me there are<br>
<div style="margin:10px; margin-top:5px; ">
	<div class="smallfont" style="margin-bottom:2px">Quote:</div>

> "array" or "val_array": array of any type.     When unnamed, then this kind of parameter must be the very last one.     Unnamed free-typed parametes cannot be followed by any other parameter.     Translates to ".*" in a plugin parameter definition rule.

if I save this [https://github.com/pinterf/Average](https://github.com/pinterf/Average) wrapper as Average.avsi
<div style="margin:20px; margin-top:5px">
	<div class="smallfont" style="margin-bottom:2px">Code:</div>
	<pre class="alt2" dir="ltr" style="margin: 0px; padding: 6px; border: 1px inset; width: auto; height: 98px; text-align: left; overflow: auto; --darkreader-inline-border-top: currentcolor; --darkreader-inline-border-right: currentcolor; --darkreader-inline-border-bottom: currentcolor; --darkreader-inline-border-left: currentcolor;" data-darkreader-inline-border-top="" data-darkreader-inline-border-right="" data-darkreader-inline-border-bottom="" data-darkreader-inline-border-left="">Function Average(array a)
{
LoadPlugin("C:\path\Average.dll")
        Average(a)
}</pre>
</div>then load it like this<br>
<br>
<div style="margin:20px; margin-top:5px">
	<div class="smallfont" style="margin-bottom:2px">Code:</div>
	<pre class="alt2" dir="ltr" style="margin: 0px; padding: 6px; border: 1px inset; width: auto; height: 82px; text-align: left; overflow: auto; --darkreader-inline-border-top: currentcolor; --darkreader-inline-border-right: currentcolor; --darkreader-inline-border-bottom: currentcolor; --darkreader-inline-border-left: currentcolor;" data-darkreader-inline-border-top="" data-darkreader-inline-border-right="" data-darkreader-inline-border-bottom="" data-darkreader-inline-border-left="">ClearAutoloadDirs()
ColorBars(width=640, height=480, pixel_type="yv12")
import("Average.avsi")
Average(Blur(1),0.5,last,0.5)</pre>
</div>it should work but I get<br>
<a href="https://postimages.org/" target="_blank"><img src="https://i.postimg.cc/4ddwGBQK/Untitled.png" alt="" border="0"></a><br>
<br>
seems I missed something or something is already missing in avs side (way to convert array to arguments maybe?)
		
</body>
</html>

**Comment by realfinder** [comment]
also: "+" mean "one or more"  "*" "zero or more" right?

Scripts arrays only do "*" ?

**Comment by pinterf** [comment]
Yes, Script arrays can do only '*': zero or more.

Function Average(array a) translates to parameter definition ".*" (zero or more of anything, this is needed for handling an arbitrary length of clip, weight, [clip, weight...] sequence)

Inside your script parameter 'a' is an explicite 'array' type, which is a single type - single variable.

Arrays in old compatible behaviour are somewhat 'hybrid' ones: arrays are always 'flattened' before recognizing them against a function definition.

Array as single variable: [clip1, value]   - one variable having two elements inside.

Array as a 'flattened' one: 
clip1, value - two variables. Count of parameters is 2 which is even.
or
clip1, value, clip2, value2 - four variables. Count of parameters is 4 which is even.

Script level keeps 'a' as an array and does not 'flatten' the array content into a non-array parameter sequence.

If Average would be written that it checks if its first (and only) parameter is an embedded array then it would work with this syntax.

**Comment by realfinder** [comment]
yes, I also think that the case

there is function that convert arguments (Array as a 'flattened') to single variable in avs+ already called "Array()" I wonder if it possible to add function for opposite case and called UnArray() or another better name?

also can script arrays get "+" (one or more) as new "*_arrays" like int_arrays to distinguish from "*_array" which mean "*" (zero or more)?

**Comment by pinterf** [comment]
Unfortunately one function can have only one result, In this case we'd need array.size number of results which is impossible.
I had many troubles on keeping the old behaviour (keep recognition of comma delimited parameters in script as an array) against the real array concept. So far this was the least failing approach that I was able to implement.

**Comment by pinterf** [comment]
I think your proposal, the ..._arrays syntax can be easily implemented, one can poll language lovers about another name, though I don't think they find a much better descriptive name.

**Comment by realfinder** [comment]
> 
> 
> Unfortunately one function can have only one result, In this case we'd need array.size number of results which is impossible.
> I had many troubles on keeping the old behaviour (keep recognition of comma delimited parameters in script as an array) against the real array concept. So far this was the least failing approach that I was able to implement.

I see, so it's impossible...



> 
> 
> I think your proposal, the ..._arrays syntax can be easily implemented, one can poll language lovers about another name, though I don't think they find a much better descriptive name.

good to know, will see what the others will say

also, I note that non-array parameters in plugins accept arrays (BM3D and fmtconv both are examples of that), while in scripts it will give error message, it will be good if script function do as plugins behavior

**Comment by pinterf** [comment]
Yep, similar behaviour would be welcomed.
I'd need an exact comparison what works for fmtconv/bm3d as a plugin and does not work an identically parameterized script function. Maybe that script function's parameter signature is not the very same as of those plugins?

**Comment by realfinder** [comment]
here https://github.com/WolframRhodium/VapourSynth-BM3DCUDA/blob/8339115ff736005b9c9f8e60e4ac8718e3a508bc/cpu_source/source_avs.cpp#L461 (note they all not array type) but they work with array https://forum.doom9.org/showpost.php?p=1949485&postcount=64
but with
```
ClearAutoloadDirs()
ColorBars(width=640, height=480, pixel_type="yv12")
convertbits(32)
Function BM3D_CPU(clip clip, clip "ref", float "sigma", int "block_step", int "bm_range", int "radius", int "ps_num", int "ps_range", bool "chroma")
{
LoadPlugin("C:\path\BM3DCPU.dll")
        BM3D_CPU(clip, ref, sigma, block_step, bm_range, radius, ps_num, ps_range, chroma)
}
BM3D_CPU(sigma=[0.5, 0.0, 0.0])
```
will give
![image](https://user-images.githubusercontent.com/2512153/131690656-730502e7-7948-4e2f-a2f5-4aff9143abe3.png)

**Comment by pinterf** [comment]
Thanks, I'm just looked into its syntax at http://avisynth.nl/index.php/BM3DCUDA
`BM3D_CUDA (clip, clip "ref", float[] "sigma", int[] "block_step", int[] "bm_range", int "radius", int[] "ps_num", int[] "ps_range", bool "chroma", int "device_id", bool "fast", int "extractor_exp")`
Thanks for the example, I'm saving it for myself.

**Comment by realfinder** [comment]
> 
> 
> EDIT: didn't you mean to write `float_array "sigma"` instead of `float "sigma"` ?

with float_array it will be endless loop and then crash since it will use the script function over and over since both dll and script functions not match

**Comment by pinterf** [comment]
Clearly, you cannot pass [] array of floats to a float "sigma". It will always report "Invalid arguments" error message.
You have to make the two function call different. We can explicitely prefix the original DLL function with the loaded DLL's name, e.g. for purposely calling BM3D_CPU of BM3DCPU.DLL you need to use
```
  LoadPlugin("C:\path\BM3DCPU.dll")
  BM3DCPU_BM3D_CPU(clip, ref, sigma, block_step, bm_range, radius, ps_num, ps_range, chroma)

```

**Comment by realfinder** [comment]
> 
> 
> You have to make the two function call different.

IIRC I did try that and it's not work too, the problem is in dll it's literally (clip clip, clip "ref", float "sigma", int "block_step", int "bm_range", int "radius", int "ps_num", int "ps_range", bool "chroma") so any thing different in the script wrapper will give endless loop and then crash

the only ugly way that seems work (I didn't test enough though) is https://forum.doom9.org/showpost.php?p=1949856&postcount=70 and maybe after adding "_arrays" ('+': one or more) it can be edit be less ugly

also for fmtconv (also has non-array parameters but accept arrays) I think it will be worst since I plan to porting Dither_resize16nr to fmtc_resamplenr wich is not simple function as the wrapper above

**Comment by realfinder** [comment]
I note another weird thing https://github.com/EleonoreMizo/fmtconv/blob/aece6c775c8e9d244c2564b759f60e62418365b2/src/main-avs.cpp#L42 planes parameter is string but it not show error with fmtc_bitdepth(16,planes=array(3,-128,1)) but it not do what it should so I think the plugins will accept anything if it array right?

**Comment by pinterf** [comment]
Back to BM3D: I checked the _CPU function signature in the DLL and "sigma" is really a single float, not an array.

**Comment by realfinder** [comment]
> 
> 
> Back to BM3D: I checked the _CPU function signature in the DLL and "sigma" is really a single float, not an array.

yes, but it work with array BM3D_CPU(sigma=[0.5, 0.0, 0.0]) unlike fmtconv, I report it here https://forum.doom9.org/showpost.php?p=1951164&postcount=29

**Comment by realfinder** [comment]
seems I misunderstanding fmtconv doc, it's not like BM3D, it's use val "." to use array inside string

**Comment by pinterf** [comment]
Ok. Then I'll investigate why `BM3D_CPU(sigma=[0.5, 0.0, 0.0]) `is allowed to work

**Comment by pinterf** [comment]
This build is giving error message when an explicite array is passed to a non-array argument.
https://drive.google.com/uc?export=download&id=19Bq8y-jUTQ0J_M3aj5foEyugIwKCG8Up
e.g. BM3D_CPU(sigma=[0.5, 0.0, 0.0]) is invalid because sigma is of a single 'f' (float) type.

**Comment by realfinder** [comment]
thanks, so that mean BM3D need to update to + array now? 

@WolframRhodium :)

**Comment by WolframRhodium** [comment]
Fixed in [`611f56`](https://github.com/WolframRhodium/VapourSynth-BM3DCUDA/commit/611f566c68fe21373c7cd603cc463a3c34e1d7e0). Thanks for the clarification.

**Comment by realfinder** [comment]
I will close this, continuation of the discussion https://github.com/AviSynth/AviSynthPlus/issues/203#issuecomment-919292755

**Comment by realfinder** [comment]
is this https://forum.doom9.org/showpost.php?p=1953137&postcount=42 plugin problem or avs+ problem?

**Comment by pinterf** [comment]
Don't know yet the exact use case, but tried to explain it a bit.
