### ISSUE TITLE
Intel compilers support

### ISSUE THREAD

**Issue by TbtBI** [AviSynth/AviSynthPlus#238]
I tried to build 1eebe2e with toolset set to either Intel C++ Compiler 19.2 or Intel C++ Compiler 2021 ( https://www.intel.com/content/www/us/en/developer/articles/technical/using-oneapi-compilers-with-cmake-in-visual-studio.html ) with no success.
The former gives error when building and the latter gives error when configuring.

Any plans to support them?

**Comment by pinterf** [comment]
Thanks. I'm downloading base toolkit right now. There is a classic icl (19.2) and a oneAPI NextGen version, I suppose both is good but the NextGen is the LLVM based one, Intel are moving towards, so I'm gonna experiment with this one. The Base Toolkit online installer includes this one. I switched off: No Python, No Math Kernel Library, No Video Processing, No Deep Neural. I'd like to figure out and document how cmake could generate a vs2019 solution.
https://www.intel.com/content/www/us/en/developer/articles/technical/using-oneapi-compilers-with-cmake-in-visual-studio.html

btw ConvertStack is an do-almost-nothing plugin with so minimal SIMD code between memory load and store that I doubt that the differences are measurable unless there is a configuration problem. debug build, no sse2 or whatever. One would see the generated asm code to see the real reason - if any.

**Comment by pinterf** [comment]
CMake support added to both the LLVM based Intel C++ Compiler 2021 and the classic Intel C++ Compiler 19.2
Read hints in CMakeList.txt, or else it may not work out-of-box.

**Comment by TbtBI** [comment]
Thanks. I can use both icl and icx without issues with the latest changes.

Btw I'm using this for testing the versions built with the different compilers:
```
# 8-bit 1080p source/ 10-bit HDR 1080p source
convertbits(16)
converttostacked()
convertfromstacked()
convertbits(10,dither=1)
convertbits(16,false)
converttodoublewidth()
convertfromdoublewidth(10)
convertbits(8)
```
Clang builds are ~14% faster than msvc builds using above script.

The latest r3488 is ~2/3% slower than older versions (r3474/r3461). I guess the culprit is the added support of frame properties (convertbits)?

**Comment by pinterf** [comment]
I don't think so. All Avisynth.dlls in your test are your own (clang) builds, with the same compiler version?
Anyway, could you tell me which one is the main culprit from the above filters? 
(I'm using ColorbarsHD(pixel_type="YUV444P10") for tests in order to rule out the input filter overhead)

**Comment by TbtBI** [comment]
I compiled avisynth.dlls with the same clang version, same cpp flags. One revision after other revision: git reset --hard babdbc0d7b39d775e5a847c74c345dfae9844338 / 1eebe2e219c321ee426e7797d6784bab120a06ff / 40adba1115f87438705bdc93c37279f2af48ad4e.
```
ffvideosource(8-bit 1080p source)
convertbits(16)
convertbits(10,dither=1)
convertbits(16,false)
convertbits(8)
```
It seems convertbits is the culprit. Tested with the above script:
- difference between r3461 and r3474 is < 1%.
- difference between r3461/r3474 and r3488 is ~4%.

The above script makes the difference between msvc and cland even greater - ~17%.

**Comment by pinterf** [comment]
Thanks. Then another request. Could you please repeat this benchmark with today's fresh commits?
I tested on my system as well; since ConvertBits was almost totally rewritten last week I had to do it along with looking into the generated asm code. (Check changelog in distrib/readmes) I'd like to know your numbers, I'm on an i7-7700 avx2 (x64 of course), clang-cl (LLVM 12) is the best overall for me, but for avx2 msvc sometimes generates quicker code. Interestingly, when clang is good here and there, they are quicker by a huge margin.

**Comment by TbtBI** [comment]
I'm with i7 7820x, W10 x64, llvm 13.0.

r3511 (daafabf) is even slower for me. r3488 is ~3% faster than r3511.

Tested with [this sample](https://files.catbox.moe/qabavy.zip) and the script from my previous comment.
```
for in %i (test.avs test.avs test.avs test.avs test.avs) do avsmeter64 %i -o
```
Removed the results with the highest and the lowest fps. Used average fps of the rest results to compare the different avisynth builds.

**Comment by pinterf** [comment]
Strange, this build performs very well for me, at least not worse than the old versions. Yet I've put back another specialization. Perhaps it is a bit quicker for the 16->10 dither=1 case. 16->8, 10->8, 16->10, etc conversions (with no full-limited conversion need) are specially templated as if the shift counts were hardcoded.
