### ISSUE TITLE
Memory usage with Prefetch

### ISSUE THREAD

**Issue by magiblot** [AviSynth/AviSynthPlus#244]
Hello,

I just realized by [reading the docs](http://avisynth.nl/index.php/SetFilterMTMode#Prefetch) that it is now possible to use Prefetch several times. This is great! Thank you so much.

I have a script that looks somewhat like this:

```py
ParallelizableFunction()
NonParallelizableFunctionThatCreatesTonsOfFilterInstances()
```
If I add `Prefetch` at the end, the script does not run any faster but consumes a lot more memory, as expected.

If I do it like this:

```py
ParallelizableFunction()
Prefetch(4)
NonParallelizableFunctionThatCreatesTonsOfFilterInstances()
```

Then the script runs faster and uses several threads. However, it still consumes a lot of memory because of `NonParallelizableFunctionThatCreatesTonsOfFilterInstances`. The memory usage goes back to normal if I remove the call to `Prefetch` or the call to `NonParallelizableFunctionThatCreatesTonsOfFilterInstances`.

I was not expecting this since `Prefetch` does not parallelize  `NonParallelizableFunctionThatCreatesTonsOfFilterInstances`. Is this normal?

I'm using the latest stable release (3.7.0).

Cheers.

**Comment by pinterf** [comment]
What happens when you put a Prefetch(small amount) at the end? (Multiple Prefetch is not my invention, I only backported the feature from Neo fork, so I'm not an expert in how it is working and why).
Maybe not related but you can visualize the filter chain with http://avisynth.nl/index.php/DumpFilterGraph

**Comment by magiblot** [comment]
Placing a Prefetch(1) at the end does not help.

Also, there seems to be a (probably related) bug where, when using Prefetch and having so many filter instances, unloading the script (in VirtualDub or any other program) takes *very* long (especially with `threads > 1`). It's as if it was using a very slow algorithm to deallocate the filters (even though Prefetch does not take them as input).

The graph does not reveal any abnormal behaviour when using Prefetch (just that there are ~1670 intermediate clips).

**Comment by pinterf** [comment]
Provide a sample pls to have me at least an overview what kind of technique can produce so many instances (for loop or a very fragmented source?). Probably there is a simple bottleneck and it can be understood and cut away. Or freeing this amount of resources really takes time.

**Comment by magiblot** [comment]
Yes, sorry for the delay. I've sent it to you via e-mail.

**Comment by pinterf** [comment]
Hmm.
First (when I had a debug build avisynth.dll) it said it had an 'assert' (this is a sanity check against parameters which is checked only in debug builds - I don't know who is sending this atm.).
Release build says (after some 27 seconds of being very busy with something): 
```
Evaluate: Unhandled C++ exception!
(c:\.......\mario.avs, line 104)
(c:\.......\mario.avs, line 129)
(c:\.......\mario.avs, line 135)
(c:\.......\mario.avs, line 275)
(c:\.......\mario.avs, line 665)

```

**Comment by magiblot** [comment]
I'm using these DePan binaries from [mvtools' latest release](https://github.com/pinterf/mvtools/releases/tag/2.7.45).
![Screenshot_20211208_171016](https://user-images.githubusercontent.com/20713561/145242538-673c12a3-ebec-471e-ac5d-1a4a56ea0516.png)

Does it at least work using the release AVS+ 3.7.0?

Also, feel free to comment out invocations to `ReplaceFramesSimple`, `doLevels` or `doStabilization` to reduce the memory footprint of the script.

**Comment by pinterf** [comment]
std::bad_alloc. probably memory issues. I'm trying to give it more memory.

**Comment by pinterf** [comment]
I unable to run this script. I have SetMemoryMax(12192), but I have total of 16GB, probably tops at a lower value. When task manager shows ~10GB memory consumption it crashes with std::bad_alloc

**Comment by pinterf** [comment]
How much memory is consumed in your system by your task manager? Interesting, AvsMeter64 does not even reach the first frame so it cannot report any memory usage.

**Comment by pinterf** [comment]
320x200 is not good:
"DePanEstimate: DYMAX must be less WINY/2 !"

**Comment by magiblot** [comment]
Okay. Sorry for the trouble.

That script also consumes lots of gigabytes of RAM for me, although I have access to a computer with 32 GB of RAM.

**Comment by magiblot** [comment]
The relevant part of the script are lines 660 to 665:

```py
v

MVDegrain(2)
Prefetch(5)

doLevels.doStabilize(last)
```


I edited line 665 of the script in four different ways:

* A: ` ` (removed it)
* B: `doLevels`
* C: `doStabilize(last)`
* D: `doLevels.doStabilize(last)` (left it untouched)

Then used different thread counts for Prefetch (line 663), opened the script in AVSMeter and wrote down the value in the `Process memory usage` indicator:

| L665 variant | Prefetch(0) | Prefetch(1) | Prefetch(2) | Prefetch(5) | Filters enabled                      |
|--------------|-------------|-------------|-------------|-------------|--------------------------------------|
| A            | 337 MiB     | 375 MiB     | 437 MiB     | 604 MiB     | MVDegrain                            |
| B            | 1042 MiB    | 1779 MiB    | 3232 MiB    | 6213 MiB    | MVDegrain, doLevels                  |
| C            | 982 MiB     | 1636 MiB    | 2936 MiB    | 5570 MiB    | MVDegrain, doStabilization           |
| D            | 1688 MiB    | 3040 MiB    | 5740 MiB    | 11167 MiB   | MVDegrain, doLevels, doStabilization |

The script's original state is `Prefetch(5)`+"variant D" so that's why it crashes on your system. Sorry for not tidying up the script a bit before sending it to you; I should have made these lines easier to find.

Therefore, you should be able to load it after editing lines 663 or 665.

The table shows that `doLevels` and `doStabilization` cause memory usage to grow like crazy even though they are invoked after `Prefetch`.

Regarding this thing I mentioned in https://github.com/AviSynth/AviSynthPlus/issues/244#issuecomment-988697191:

> Also, there seems to be a (probably related) bug where, when using Prefetch and having so many filter instances, unloading the script (in VirtualDub or any other program) takes very long (especially with threads > 1). It's as if it was using a very slow algorithm to deallocate the filters (even though Prefetch does not take them as input).

I realized this only happens when `doStabilize` is invoked. Possibly related is the clip defined in line 173 (`b = StabInter(nostutter)`), which is reused by all invocations to `ReplaceStabCrop` (which passes it to `DePanEstimate`). I did that on purpose convinced that it would consume less memory. However, I did not like the results and changed it so that it is not reused anymore (in my local version of the script). After this change, the script unloads much faster.

**Comment by pinterf** [comment]
Thanks, this analysis will help a lot.

**Comment by pinterf** [comment]
Non-debug build can cope with it with Prefetch(4). It is no even slow on start and exit- tested with avsmeter64

**Comment by magiblot** [comment]
Regarding load/unload slowness (although it may be a separate issue), this screen recording summarises what I'm seeing:

https://user-images.githubusercontent.com/20713561/145599743-9f1422b1-1e51-4f0e-abba-5deb008d9e82.mp4

**Comment by pinterf** [comment]
To me it seems also that doStabilize makes the slowness on exit, the memory consumption has a slight slope there.

**Comment by pinterf** [comment]
I thought it takes 10-20-30 seconds' time but this amount of slowness - a couple of seconds at most - was acceptable for me. I I think is proportional of the internal complexity.

**Comment by DJATOM** [comment]
Apparently you're using Wine and it might cause additional hidden bugs, which usually hard to debug. 
So you should try to reproduce with native Linux build or use Windows. If it still happens, then it worth digging deeper into Avisynth code. Otherwise it's most likely a Wine overhead.

**Comment by pinterf** [comment]
DepanEstimate has many large internal buffers for fft cache and structures. Allocations, plans, destroying plans are using fftw3 calls so the slowness can come from that fact as well. But probably the sheer amount of actions makes it slower.

**Comment by magiblot** [comment]
Okay, I will try to run the script natively on Linux like DJATOM suggested and profile it to find out where the slowness comes from.

**Comment by pinterf** [comment]
I was experimenting with 

begin with
`SetFilterMTMode("DepanEstimate",3) # serial mode`

and then

```
MVDegrain(2)
Prefetch(4)
doLevels
Prefetch(1,10)
doStabilize(last)
Prefetch(3,20)
```
int the end
Play with the numbers, I just copy-pasted the latest set I was trying with, even if they are insane (20? what for)

**Comment by magiblot** [comment]
I managed to get it to run on Linux. All players I tried (`mpv`, `ffplay`) exit as soon as I close them. I wonder if this is because the unloading slowness is actually a Wine-only issue like DJATOM suggested or because these players don't bother unloading the script.

Anyway, memory usage continues to be an issue. I would like my script to run faster, but I can't use more threads because it runs out of memory, even though the filters consuming so much memory are placed after `Prefetch` and not before.

**Comment by magiblot** [comment]
Setting the non-parallelizable filters to `MT_SERIALIZED` works around the issue:

```py
SetFilterMTMode("AutoLevels", MT_SERIALIZED, force=true)
SetFilterMTMode("ReplaceFramesSimple", MT_NICE_FILTER, force=true)
SetFilterMTMode("DePanEstimate", MT_SERIALIZED, force=true)
SetFilterMTMode("DePan", MT_SERIALIZED, force=true)
```

I suspect the reason for this is `ScriptEnvironment::NewThreadPool`, which calls `EnableMT` on **all** `MTGuard` instances, not just the ones affected by the current `Prefetch` call:
```c++
// Since this method basically enables MT operation,
// upgrade all MTGuards to MT-mode.
for (MTGuard* guard : MTGuardRegistry)
{
  if (guard != NULL)
    guard->EnableMT(nMaxFilterInstances);
}
```

**Comment by pinterf** [comment]
1.) A hint on Depan*** behavior: 
DepanEstimate and Depan do not report their MT mode automatically so they will behave as default mt mode (MT_MULTI_INSTANCE).
This is why I - like you - have intentionally set it to MT_SERIALIZED at the beginning of the test script.
But this is just a workaround

2.) Could you pls try adding that line (  nMaxFilterInstances = 1; )?
Still debugging whether it has any side effect somewhere.

Anyway, as the comment says, the last Prefetch value which appeared before a function could never be decreased.

I think the expected behavior is the following: default thread count must be reset after each Prefetch to 1. Then if another Prefetch is found later, it must upgrade those MT_MULTI_INSTANCE filter instances to the requested parameter since last Prefetch.
(And I see that the actual instance count is always upgraded to a power-of-two, 3->4, 5->8. I'm not yet seeing the real reason of that but if it asserted in MTGuard::EnableMT so it may be an important prerequisite.

This modification yielded a real gain in memory consumption when I put Prefetch(4) after MDegrain and no Prefetch or Prefetch(2) before the end.
Results: 10 GB (62 fps) (original) vs. 2 GB (60 fps) (no second prefetch) vs. 5.6 GB/65 fps (second prefetch(2))

I hope I can check it a bit deeper and clear the issue.

```
  // Since this method basically enables MT operation,
  // upgrade all MTGuards to MT-mode.
  for (MTGuard* guard : MTGuardRegistry)
  {
    if (guard != NULL)
      guard->EnableMT(nMaxFilterInstances);
  }

  nMaxFilterInstances = 1; 
  // after Prefetch reset to 1.
  // or else a filter chain ended with a smaller thread count (on multiple Prefetch) or no Prefetch
  // will remember the latest prefetch when it is bigger than the latest one value

```

**Comment by pinterf** [comment]
I went further because even if thread count was limited by this mod, the number of filter instances kept being 2^N.
Prefetch(3) created 4 filter instances. Prefetch 4 to 7 created already 8 instances from MT_MULTI_INSTANCE filters
Prefetch 8 to 15 created 16 instances.

Tested with this torture script (1000+ filter instances!) which ends like this (though I immediately downsized the clip to be able to test multiple threads with my limited RAM (SetMemoryMax(12000)).

Three versions were tested; 
- original (excessive threads and even excessive filter instances after first prefetch)
- halfway-there (thread count O.K. but still excessive filter instance count for MT_MULTI_INSTANCE)
- actual (thread count O.K., filter instance count matches with Prefetch)
```
.. setmemorymax, source, resize
MVDegrain(2)
Prefetch(6)
doLevels
doStabilize(last)
#Prefetch(1) # 1..4

# for testing purposes DePanEstimate was not set to MT_SERIALIZED (kept as MT_MULTI_INSTANCE)
# Prefetch(6) first part
# Prefetch(N) second part after doLevels and doStabilize where N goes from 4 to 1 then no prefetch line.
#         prefetch Number-Memory_MB/fps  (-)means no prefetch
# orig  : N(4)-10782/64,6 (3)-11042/57,0 (2)-10785/65,8 (1)-11000/66,4 (-)-10964/54,8
# mod1  : N(4)-10782/64,6 (3)- 5783/72,6 (2)- 5704/75,9 (1)- 3002/72,8 (-)- 1635/68,1
# mod2  : N(4)- 5897/67,3 (3)- 4504/70,9 (2)- 3138/72,9 (1)- 1696/70,2 (-)- 1642/65,7

# mod1: limited thread count for 2nd or no prefetch
# mod2: mod1 + MT_MULTI_INSTANCE filter intances limited to N and not the next power of two N

# in mod1 still:
#       Prefetch 3 created 4 filter instances
#       Prefetch 4 to 7 created 8 filter instances
#       Prefetch 8 to 15 created 16 filter instances, etc..
# When the filter was memory-allocation heavy
# (like DepanEstimate which allocates large fftw3 buffers in its constructor)
# it caused excession memory consumption because unnecessary filter instances were created

```

**Comment by magiblot** [comment]
So far so good. Thanks!
