### ISSUE TITLE
VersionNumber() returns 2.6

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#262]
What's the reasoning behind ``VersionNumber()``  returning 2.6? I know that r1576 had a version number of 0.1 which would of been useless since 2.6 > 0.1. But know that AviSynth+ uses a different versioning, it would make sense for ``VersionNumber()`` to return 3.71.

**Comment by pinterf** [comment]
VersionNumber returns a real number double (float), so it cannot cope with our three part versioning. 3.7.1 (=3.71?) would be the same as 3.7.10 (3.710?)

It seems it is just a compatibility function.

**Comment by Reel-Deal** [comment]
I though classic AviSynth has always used a three part versioning, 2.6.0 for example. ``VersionNumber()`` returns 2.600000 for both 2.6.0 and avs+. I installed 2.6.1 and it returns 2.610000.

**Comment by pinterf** [comment]
Then the old 2.5.8 changed in due time before it reached 2.5.10 :)

**Comment by Reel-Deal** [comment]
I guess it did :). I just thought it was odd that it still returned 2.6 and there no minimalist way of getting the version number without using FindStr as [shown on the wiki](http://avisynth.nl/index.php/Internal_functions#VersionString).

I'll leave this open for a bit in case @qyot27 wants to comment on it.

**Comment by qyot27** [comment]
I had just assumed it was linked to the idea of keeping the 2.6 markers around for compatibility with old/odd programs that hardcoded themselves to work with 2.6 but would otherwise work fine with Plus (akin to why `AVISYNTH_INTERFACE_CLASSIC_VERSION` is a thing).

**Comment by Reel-Deal** [comment]
Thanks for the replies. I'll put a note on the docs :)
