### ISSUE TITLE
Compare: text formatting seems to be off for HBD colorspaces.

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#265]
I was working on the Compare docs and notice something was odd. The formatting for the text is off when used with 16-bit. I tried RGB64, RGBP16, and YUV444P16 and same results. Also the metrics for 16-bit seem funny but I don't know if they are correct or not :).

Here's the script I used and below that a picture for convenience.

```
a8  = Colorbars(pixel_type="RGBP8").Trim(0, -1)
b8  = a8.Sharpen(1.0)
a16 = Colorbars(pixel_type="RGBP16").Trim(0, -1)
b16 = a16.Sharpen(1.0)
c8  = Compare(b8, a8) 
c16  = Compare(b16, a16).ConvertBits(8)

Interleave(c8, c16)
Crop(0,0,0,height/3)
Subtitle("Compare 8bit", align=1, first_frame=0, last_frame=0) 
Subtitle("Compare 16bit", align=1, first_frame=1, last_frame=1) 
```

![compare](https://user-images.githubusercontent.com/3104705/153708637-1f41a627-1457-4d7a-bfeb-c75338e23af2.png)

Edit: I also noticed that with Greyscale (Y) clips, ``channels`` has to explicitly set to "Y" otherwise it gives this error: 

> Compare: invalid channel: U for greyscale clip

**Comment by qyot27** [comment]
The piece of code controlling the text alignment for `Compare()` is here:
https://github.com/AviSynth/AviSynthPlus/blob/master/avs_core/filters/text-overlay.cpp#L2890

16-bit values need larger numbers, and snprintf uses right alignment by default (the only place on either side of that block that's left-aligned is the frame count).

**Comment by pinterf** [comment]
Yes, for 8 bits it was enough to have at most three digits.

**Comment by Reel-Deal** [comment]
@pinterf 

Here's an issue:

> I also noticed that with Greyscale (Y) clips, channels has to explicitly set to "Y" otherwise it gives this error: Compare: invalid channel: U for greyscale clip

I think the channels parameter should be ignored when the source is Y.

**Comment by pinterf** [comment]
Thanks. When not given, 'channels' default is "RGB" for rgb, and "YUV" otherwise. There was no greyscale case. Now the default is "Y" for greyscale clips.
Fixed in 8a350bf435e96241e0ed0895ddeac2ae6f692096

**Comment by Reel-Deal** [comment]
Thanks for the quick fix.

Quick question, does Compare support 10-14 bit clips? It seems to work with 10-14 bits (at least no errors) but I don't see anything definitive in the commit history. Only thing I found is "Compare() port to 16 bits (RGB48/64,YUV+A/Planar RGB+A."  in 6f393d8e6770096b24cef9b29adb51a379702eed.

**Comment by pinterf** [comment]
As I can see, show_graph is not working well for 10-14 bits: draws out-of-range pixel values (always 65535: 16 bit maximum) instead of 1023 (10 bit max), 4095 (12 bit max), 16383 (14 bit max).

**Comment by pinterf** [comment]
test5, x64 no-xp only. I hope you are on a such a system, tell me when you are in xp or win32.
https://drive.google.com/uc?export=download&id=1E3jjdRFbd4ge0b45TY2w3uxe5WZkC3y3

**Comment by Reel-Deal** [comment]
Ahh yes, I can see now that the graph is not working:
![images](https://user-images.githubusercontent.com/3104705/154671711-af3b0e95-9f00-40bc-b82a-32a8167cd8be.png)

I didn't let the clip play through went I tested 10-14bits. And then I just settled on 8 bit clip since the 16-bit one does not fit in the small frame which I will use as an example for the docs. Which brings me to my next question. I understand that numbers are bigger when > 8 bits. but why is there so much dead space? In the 8bit image there is a minimum of one space between the numbers and the ( and /.

> test5, x64 no-xp only. I hope you are on a such a system, tell me when you are in xp or win32.

Thanks! and I'm on W7 x64.

**Comment by pinterf** [comment]
16 bit values e.g. avg must have space for up to 65535, e.g. 65534.232 instead of 253.11 (two more digits)

**Comment by Reel-Deal** [comment]
Gotcha... so just tested test 5, seems like you added support for 10-14 bits. Tested YUV/RGB with those bit depths and all seems to be working. Very nice pinterf!

**Comment by Reel-Deal** [comment]
Indeed it was:
![compare 00](https://user-images.githubusercontent.com/3104705/154674892-f9eaaa0e-2bb7-4b90-aa68-e11f8dbe810c.png)
