### ISSUE TITLE
YUV to RGB conversion at 32 bpc produces out-of-range values

### ISSUE THREAD

**Issue by magiblot** [AviSynth/AviSynthPlus#267]
Hi!

Consider the following script:

```py
BlankClip(pixel_type="YV24")
Expr("255", "128", "128")
ConvertBits(32)
ConvertToPlanarRGB()
Expr("x 1 > 1 0 ?")
```

Look at the last line. Since floating-point pixel values should be in the range [0, 1], one would expect that the condition `x > 1` is never met. However, it does for me so the resut I get is a white clip.

I'm using commit 94241fd4a9ca29ebfda45d2c53bbeb387b8bc873 (current master).

Thank you!

**Comment by pinterf** [comment]
Float in general is not clamped unless it has special purpose. There is no out-of-range for float.
You can expect such values during an YUV-RGB conversion.

**Comment by magiblot** [comment]
Oh, you are right. Sorry for the trouble.
