### ISSUE TITLE
propNumElements/propGetType as normal script function

### ISSUE THREAD

**Issue by TbtBI** [AviSynth/AviSynthPlus#272]
```
FFVideoSource(video)
propset("_ColorRange", 1) # in case no _ColorRange frame prop
SmoothD2(quant=5, zw=1, ncpu=1) # old plugin that is not aware of frame props
fs = propNumElements ("_ColorRange")  > 0 ? propGetInt("_ColorRange") == 0 : false
Subtitle(String(propGetType ("_ColorRange")  > 0))
```
SmoothD2 - https://www.dropbox.com/s/ui8chlbzopuqs5a/SmoothD2-a3_x64.zip?dl=1

Hi. If you open the above script in AvsPmod and hit F5 few times you will see that subtitle returns one time "true", other time "false". Using both propNumElements and propGetType have the same behavior.
If you use the last two lines (fs... and Subtitle...) within ScriptClip, subtitle always returns "false".
If you put propClearAll() before the line beginning with "fs = ...", subtitle always returns "false".
If you remove the line beginning with "fs = ...", subtitle always returns "false".

**Comment by pinterf** [comment]
Not only unaware of frame props.
SmoothD2 is an AviSynth 2.5 plugin which can use hardcoded ("baked") code for frame manipulation instead of Avisynth interface calls. Behavior is uncontrolled and random.

**Comment by TbtBI** [comment]
Then in case of the use of such filters one should explicitly call propClearAll() or use to ScrtiptClip in order to use the frame properties?

**Comment by pinterf** [comment]
Or ask someone to do a little modification in the source and recompile the filter to be at least an Avisynth 2.6 plugin.

**Comment by TbtBI** [comment]
Ok, thanks.
