### ISSUE TITLE
Fade filters: no color_yuv option

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#273]
The Fade filters are the only filters remaining filters without the ``color_yuv`` option.

Edit:
Better yet, maybe the ``colors`` parameter across all filters take a color as an input? The reason I say that is that I think ``color_yuv`` may be flawed (with maximum pixel values). It was first mentioned here: https://forum.doom9.org/showthread.php?p=1959142#post1959142

The response was that "colors are simply treated as rec601 limited range ones." ... Which is true, but only if ``color`` is used on YUV. I was under the impression that ``color_yuv`` also passed unscaled values. I did some tests and the findings seems to suggest that there are some discrepancies with ``color_yuv``. The columns RGB and YUVL are with the ``color`` parameter and YUVF  is with ``color_yuv``. As you can see, everything seems correct for YUVF minus the max values for 10-16 bit.

``color or color_yuv = $FFFFFF``
| Max Values |       |       |       |
|------------|-------|-------|-------|
| Bits       | RGB   | YUVF  | YUVL  |
| 8          | 255   | 255   | 235   |
| 10         | 1023  | 1020  | 940   |
| 12         | 4095  | 4080  | 3760  |
| 14         | 16383 | 16320 | 15040 |
| 16         | 65535 | 65280 | 60160 |

``color or color_yuv = $808080``
| Half Values |       |       |       |
|-------------|-------|-------|-------|
| 8           | 128   | 128   | 126   |
| 10          | 513   | 512   | 504   |
| 12          | 2055  | 2048  | 2016  |
| 14          | 8223  | 8192  | 8064  |
| 16          | 32896 | 32768 | 32256 |
|             |       |       |       |

``color or color_yuv = $000000``
| Min Values |     |      |      |
|------------|-----|------|------|
| Bits       | RGB | YUVF | YUVL |
| 8          | 0   | 0    | 16   |
| 10         | 0   | 0    | 64   |
| 12         | 0   | 0    | 256  |
| 14         | 0   | 0    | 1024 |
| 16         | 0   | 0    | 4096 |

**Comment by pinterf** [comment]
'color_yuv' and 'colors' added
The Fade filter family directly invokes BlankClip so it was easy to add then pass the very same parameters.

**Comment by pinterf** [comment]
>As you can see, everything seems correct for YUVF minus the max values for 10-16 bit.

A YUV 8 to 10-16 bit conversion is done using the usual bit shift. There is no way that would make 255 to 65535 (max 16 bit).
When you pass $FF as Y color that it is never treated as full range because there is no option or hint in BlankClip to note how to interpret the color information. No full-range option => no possibility to tell the filter that Y=255 must be 65535 in a 16 bit world.

**Comment by Reel-Deal** [comment]
> 'color_yuv' and 'colors' added The Fade filter family directly invokes BlankClip so it was easy to add then pass the very same parameters.

Cool, thanks pinterf.

> it makes no sense of talking about 8 bit 'half values' in the context of color_yuv or rgb color

I only used that terminology to label the table.

> There is no way that would make 255 to 65535 (max 16 bit).
When you pass $FF as Y color, it is never treated as full range because there is no option or hint in BlankClip to note how to interpret the color information. No full-range option => no possibility to tell the filter that Y=255 must be 65535 in a 16 bit world.

Thanks for the explanation. It makes a bit more sense now. The reason I included those tables was to show that $80 maps to 32768 in 16-bit (and all other bit depths. But when it comes to $FF it does not map to 65535. I guess I need to add a note to the color_yuv parameter. Specifically Blankclip and AddBorders because I've used them in the past to make masks (granted this was before the colors parameter). So now that Fade has ``colors``, it leaves AddBorders and Letterbox only having the color_yuv option.

Sidenote about ``colors``, would be nice if it ignored any extra values that are specified, for example if [0,0,0] are given but the clip is Y.

**Comment by pinterf** [comment]
This one?
- BlankClip: allow 'colors' size more than actual planes.
  If an array is larger, further values are simply ignored.
- BlankClip, AddBorders, LetterBox: no A=0 check for non-YUVA

AddBorders and LetterBox 'colors' addition is not so straightforward though, I postponed it a bit.

**Comment by pinterf** [comment]
test10
https://drive.google.com/uc?export=download&id=1HGQ8n0zkvl6ouK-3-2MnmOzFZA_TF21h

**Comment by Reel-Deal** [comment]
Thanks, I will check it out when I wake up later on :)

**Comment by Reel-Deal** [comment]
>AddBorders and LetterBox 'colors' addition is not so straightforward though, I postponed it a bit.

I'm closing this issue since the initial issue was taken care of. We left off at adding 'colors' to AddBorders and LetterBox since they are the last 2 filters remaining without such option. If down the road you have time/interest in making the filters complete, just let me know and I'll open a new issue.
