### ISSUE TITLE
TimeStretch: missing function from avs 2.6.1

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#278]
Hi, I was updating the TimeStretch docs and noticed that there was a new function added to TimeStretch in avs v2.6.1:

http://avisynth.nl/index.php/TimeStretch

```
TimeStretch(clip clip [, int tempo_n, int tempo_d, int rate_n, int rate_d, int pitch_n, int pitch_d, int sequence, int seekwindow, int overlap, bool quickseek, int aa ]) 
```
>  Tempo_n, Tempo_d, Rate_n, Rate_d, Pitch_n and Pitch_d
>
>  When needing more accuracy you can use the rational pair parameters tempo_n, tempo_d, rate_n, rate_d, pitch_n and pitch_d instead. All parameters are integers and have default value 1. Internally tempo is calculated as double(tempo_n/tempo_d) (rate and pitch likewise), before further processing. Seeking should be sample exact. 

However, this was not added to AVS+. I also noticed that the latest SoundTouch is v2.3.1 (avs is 2.1.3): https://codeberg.org/soundtouch/soundtouch/tags

```
5.1. SoundTouch library Change History

2.3.1:

    Adjusted cmake build settings and header files that cmake installs

2.3.0:

    Disable setting "SOUNDTOUCH_ALLOW_NONEXACT_SIMD_OPTIMIZATION" by default. The original purpose of this setting was to avoid performance penalty due to unaligned SIMD memory accesses in old CPUs, but that is not any more issue in concurrent CPU SIMD implementations and having this setting enabled can cause slight compromise in result quality.
    Bugfix: soundtouch.clear() to really clear whole processing pipeline state. Earlier individual variables were left uncleared, which caused slightly different result if the same audio stream were processed again after calling clear().
    Bugfix: TDstretch to align initial offset position to be in middle of correlation search window. This ensures that with zero tempo change the output will be same as input.
    Bugfix: Fix a bug in TDstrectch with too small initial skipFract value that occurred with certain processing parameter settings: Replace assert with assignment that corrects the situation.
    Remove OpenMP "_init_threading" workaround from Android build as it's not needed with concurrent Android SDKs any more.

2.2:

    Improved source codes so that compiler can autovectorize them more effectively. This brings remarkable improvement e.g. ARM cpus equipped with NEON vfpu: Bencmarked 2.4x improvement in execution speed in ARMv7l vs the previous SoundTouch version for both integer and floating point sample types.
    Bugfix: Resolved bad sound quality when using integer sample types in non-x86 CPU
    Bugfix: Fixed possible reading past end of array in BPM peak detection algorithm
```

**Comment by pinterf** [comment]
Update to v2.3.1 is done. Where can I find 2.6.1 TimeStretchPlugin source?

**Comment by Reel-Deal** [comment]
I not sure what is going on, when I use TimeStretch(tempo_n=105) on avs 2.6.1 I get an error message that TimeStretch does not have a  tempo_n parameter.  I tried seeing the source code but SourceForge only has offline access to CVS. The way it is written in the wiki (Wilbert wrote)  it makes it seem like there is a new function in avs 2.6.1.

```
# 2.6
TimeStretch(clip clip [, float tempo, float rate, float pitch, int sequence, int seekwindow, int overlap, bool quickseek, int aa ])
# 2.6.1
TimeStretch(clip clip [, int tempo_n, int tempo_d, int rate_n, int rate_d, int pitch_n, int pitch_d, int sequence, int seekwindow, int overlap, bool quickseek, int aa ]) 
```
I don't know how to access the CVS source code on SourceForge but that is the only place I know that has it. https://sourceforge.net/p/avisynth2/cvs/

I know ultim merged some code from 2.6.1 back in 2016 but the parameters are still like 2.6.

> Where can I find 2.6.1 TimeStretchPlugin source?

I don't think there was ever a 2.6.1 standalone plugin. Only one I know of is Wilbert's but it's from 2015 which I don't think has the 2.6.1 changes.

I could ask Wilbert to host the 2.6.1 source, if need be...

**Comment by qyot27** [comment]
I've kept a mirror of the CVS on Git as a branch on my own repo, as it was largely how I facilitated some of the merges for the RCs back then:
https://github.com/qyot27/AviSynthPlus/tree/classic_avisynth/

I *think* that it has all the commits, but I'm not sure.  The last time anything was merged it was done in a different way than I'd usually handled mergeback pull requests.

TimeStretch:
https://github.com/qyot27/AviSynthPlus/blob/classic_avisynth/src/audio/avs-soundtouch.cpp#L206

**Comment by pinterf** [comment]
Yep, that's more recent than https://github.com/jeeb/avisynth/blob/master/src/audio/avs-soundtouch.cpp

**Comment by pinterf** [comment]
Soundtouch update to 2.3.1 in bc1224b9b801a9a6283ec0b0efa2e90e4a7371ba
Unlike the actual upstream source default, internal accumulator is kept `double` instead of `float` (no change, same as it was before)
(`StTypes.h`: `typedef double LONG_SAMPLETYPE;`)

**Comment by qyot27** [comment]
That's going to create issues moving the plugins to using external system libraries, isn't it?  Because SoundTouch is easy to use as an external library on Linux where we can just install from the repos and then the plugin can use the system's version.  I'd tried to do that a couple years ago and the only thing that stopped it was that pkg-config wasn't working correctly for cross-compiles (so it never got to the point of even testing under MSVC).

The end goal is to really try and get TimeStretch and ImageSeq to use standard system library detection so we don't have to continue embedding the sources or having .dlls checked into the git repo (and bonus: doing that with ImageSeq would make it possible to link DevIL in statically and not have to worry about DevIL.dll anymore).

**Comment by Reel-Deal** [comment]
> EDIT: This commit could be integrated: [qyot27@82d0ee4](https://github.com/qyot27/AviSynthPlus/commit/82d0ee458b2dfd785026a4df691ea27247fe6db7)

So there is such a function. Seems the source and the wiki were updated but the avs 2.6.1 alpha release lack that update.

**Comment by Reel-Deal** [comment]
I went ahead and updated the documentation as if the rational pair syntax will be available in 3.7.3. I'll leave the issue open until the changes are committed.

**Comment by Reel-Deal** [comment]
> EDIT: This commit could be integrated: [qyot27@82d0ee4](https://github.com/qyot27/AviSynthPlus/commit/82d0ee458b2dfd785026a4df691ea27247fe6db7)

@qyot27 can you please merge this commit?

**Comment by Reel-Deal** [comment]
I wanted to see if I could do a PR on this issue so we can close it, but then found out that Timestretch is a plugin now and not part of the core. So it was not as easy as I thought it would be. I think I  managed to add the new function but would appreciate it if someone looked over it: https://github.com/Reel-Deal/AviSynthPlus/commit/030cee7e1eb5d8599177504d96eea137f29d5892

I'm not sure about one difference. In the original commit, lines 180-182: https://github.com/qyot27/AviSynthPlus/commit/82d0ee458b2dfd785026a4df691ea27247fe6db7#diff-895102cfab8bf0e38bd176fe8b443998d0dfd16c5dea716638c499c62638ab30R175

In avs+ the values are not divided by 100 but it seems that it was moved to the AVSsoundtouch function (lines 69-71): https://github.com/AviSynth/AviSynthPlus/blob/master/plugins/TimeStretch/TimeStretch.cpp#L68

Not sure what to do there :)

**Comment by qyot27** [comment]
The division by 100 and the change from AsFloatf to AsFloat was probably of a pair because it was *I guess* attempting to move a percentage to a float?

Apart from that, tabs->spaces.

**Comment by radpopl** [comment]
Is TimeStrech available as a dll somewhere?
