### ISSUE TITLE
Ubuntu 20.04 issue compiling ffms2 errors pointing to avisynth source

### ISSUE THREAD

**Issue by demianph** [AviSynth/AviSynthPlus#294]
All the preceding steps (compile and install) go fine for AviSynthPlus and ffmpeg.

Following instructions for Ubuntu:
[ffms2 compile error.log](https://github.com/AviSynth/AviSynthPlus/files/9226867/ffms2.compile.error.log)
    
    I get a ton of errors and a failure.
    See attached log for output.

**Comment by qyot27** [comment]
Those aren't errors in the avisynth headers or in ffms2's avisynth plugin sources, those are just compiler warnings.

The error is in the linking phase against libavcodec:
```
/usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:650: src/core/libffms2.la] Error 1
```

Which, [as was pointed out over on Doom9](https://forum.doom9.org/showthread.php?t=182574), requires FFMS2 to be configured with `LDFLAGS=-Wl,-Bsymbolic` when linking against a static build of FFmpeg.

**Comment by demianph** [comment]
> 

My apologies. I didn't know the errata was over on Doom9 forums. I will go there.
It might be helpful to have a note to go there(doom9, not everyone comes here from there) in case of issues on the page with the instructions.

**Comment by qyot27** [comment]
It's not really so much that the errata is over on Doom9, although that is generally where a lot of the development talk ends up being.  It was more simply that that issue had been raised there recently.

The compilation instructions in `posix.rst` are in need of some updating.  I don't know why FFMS2's configure doesn't want to detect that `-Wl,-Bsymbolic` is necessary for the case of linking a static library into the .so, as it was able to do that before.  Unless that's actually a bug in the linker that's interfering with configure doing that check.  I have no idea.
