### ISSUE TITLE
Exceptions from `AvisynthPluginInit3()` not displayed!

### ISSUE THREAD

**Issue by Enyium** [AviSynth/AviSynthPlus#315]
When `env->ThrowError()` is used or an `AvisynthError` is thrown in `AvisynthPluginInit3()`, there's only the message `"'%s' cannot be used as a plugin for AviSynth."`.

Even `env->AddFunction()` though, that'll always be called in `AvisynthPluginInit3()`, may throw `"%s has an invalid parameter string (bug in filter)"` (see `PluginManager.cpp`). It would definitely be useful to be able to read that message during development. But the way things are, this message will practically never be shown.

In my Rust crate that can be used to write plugins, I also let a plugin author return an error string from the plugin init function the same way it's possible with a plugin function (that can be called from an .avs script). Returning an error string from a plugin function gives the nice typical red error text containing the string. This should also be possible with the plugin init function. There are also errors my crate handles for the plugin author, like insufficient AviSynth+ interface version with the request to the user to update their AviSynth+ installation. So, some error strings from the plugin init function are from my crate, others can be from the plugin author.

# Suggestion

When loading a plugin, please catch `AvisynthError`s (besides the already existing `catch (...)` with literal dots) and append the thrown message as a second line or otherwise to "...cannot be used as a plugin..."

**Comment by pinterf** [comment]
See commit 78c0d9f252bc2a6e8f7b76a2fa4c610283921836

**Comment by Enyium** [comment]
What about long lines? Are you opposed to write `"'%s' plugin loading error:\n%s"`? Otherwise, the video may get very wide. It already contains a path at the beginning. Such an initialization failure message from the plugin author could also contain multiple lines itself. It would be strange to have the message's first line after `...plugin loading error: ` and the rest on their own lines.

---

In case of `!avsexception26_message.empty()`, there could be this comment:

```cpp
            // Message could be from plugin author or, e.g., from env->AddFunction()
```
