### ISSUE TITLE
Histogram("color2") shift in markers with parameter bits > 8.

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#327]
Hi there pinteft, 

Back again with another minor Histogram issue :). A while back I had mentioned that the ``Histogram("color2")`` had a small shift in the 15 degree markers compared to avs 2.6. See first post in #268. I had never really used the ``bits`` parameter until recently and noticed that the dots shift even more when bits > 8. Also the corners of the limited range square become unaligned at the corners.

Here's color2 at 9 bits:
```
ColorBarsHD()
Histogram("color2", keepsource=false, bits=9)
```
![color2](https://user-images.githubusercontent.com/3104705/216280602-5de2d9bd-787a-475a-b2fd-e3aa317c43c7.png)

As you can see, some of the dots have disappear into the center of line and others outside of the circle when in avs 2.6 they are all positioned in the inner edge. Also you can start to see the corners becoming misaligned. Here's one of the corners at ``bits=12``.

![color2-10 (2)](https://user-images.githubusercontent.com/3104705/216282376-43cd5898-decf-419d-9932-c6af96dd64cd.png)

**Comment by pinterf** [comment]
Thanks for the report, let's investigate it. So even at 8 bits we have differences from avs 2.6.

**Comment by Reel-Deal** [comment]
Thanks for taking a look at the issue and fixing it :)
