### ISSUE TITLE
Crash when prefetch is used 

### ISSUE THREAD

**Issue by Asd-g** [AviSynth/AviSynthPlus#345]
In AvsPmod when I hit F5 (sometimes once, sometimes several times) [r3950](https://github.com/AviSynth/AviSynthPlus/commit/7325e56fb10c5d3c01278d54d55ea291214e3284) is crashing ([r3944](c38e6a3f9fa6057252863f3f6f5cb956582f546f) is fine).
Script to reproduce:
```
ColorBars(640, 480, "YV12")
for (i = 0, 100)
{
Expr(last, "x x + x x + +")

Prefetch(2)
}
```
Increasing the prefetch number makes the crash more often.

**Comment by pinterf** [comment]
Thanks, I see it, theoretically this should never happen (I put there an assert as well), I love such issues :)

**Comment by Asd-g** [comment]
Thanks.
