### ISSUE TITLE
XP issue with 3.7.3 and vcredist 2019 issue

### ISSUE THREAD

**Issue by anonyme-x22** [AviSynth/AviSynthPlus#367]
Hi, 
I've tested the 3.7.3 on xp 64 using 32bit plugins.
Unfortunately this one crash windows media player with HQ overlay for gpu acceleration and video filter by gpu.
So i reinstalled the 3.7.2 and did have an avi import filter error!
Tried everything even the first mt version with the same error.
I finally found that is was vc redist 2019 which cause the issue.
Desinstalled vc redist 2015-2019, and reinstalled vc redist 2017, and it's working.
Can you please see why 3.7.3 crash with gpu acceleration?
Anyway that seem to be the end of xp support!

Edit: Finally found the issue for 3.7.2 or older it's VCRedist 2017+avisynth+Lavfilter, but with this install order for the last two program, this way lav filter is used in addition to avisynth, enabling gpu acceleration and 4 times more performances (depending on gpu).
However for the 3.7.3 it' an avi import filter even with vc redist 2015-2019. will try the package with included vcredist...

Edit2: finally found for 3.7.3, there is an issue with vc redist 2019, which seems to be the 14.29 latest xp support. With this one you get an avi import filter. However using vc redist 2017 64bit instead of 2015-2019 14.29, it's working. you need to uninstall/reinstall lavfilter, and its ok with gpu.
The xp vc redist package don't even install vc redist which seems to be newer than 14.29, however you need to install this package. 

Thanks for your reading,
Have a good day,
Rgds,

**Comment by pinterf** [comment]
Seems that the problem was solved by an uninstall-install process and applying the last available XP-working redistributable.
