### ISSUE TITLE
Obsolete part in doc for 3.7, need substitution for it

### ISSUE THREAD

**Issue by MarianD** [AviSynth/AviSynthPlus#369]
In AviSynth documentation for version 3.7, in

- **Overview →  Scripting reference**

is still the obsolete part

- **Block statements**

about workarounds for the previously missing construction as` if-elif-else` or `for` loop.

Now, when such constructions (like in the previously used GScript) are implemented, this part is useless.
It has to be replaced with yet non-existing part about those (relatively new) constructions.

**Comment by pinterf** [comment]
The documentation is continously (but slowly) updated as our time allows it. There is still a huge amount of stuff that needs to be updated. Contribution is welcomed however :) At the moment there are other areas in the update queue.
