### ISSUE TITLE
readthedocs build does not work

### ISSUE THREAD

**Issue by pinterf** [AviSynth/AviSynthPlus#371]
The latest rst updates do not appear at Avisynth online documentation.

E.g. I created a dummy 3.7.4 part in the version history but our readthedocs page is not showing that.
https://avisynthplus.readthedocs.io/en/latest/avisynthdoc/overview.html#versions-history

I checked the webhook publishing is OK, as I see here:
https://github.com/AviSynth/AviSynthPlus/settings/hooks

Then I found a build history over there: "build failed" as seen in
https://readthedocs.org/projects/avisynthplus/builds/22268009/
`Error The configuration file required to build documentation is missing from your project. Add a configuration file to your project to make it build successfully. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html
`
It says, we need a .readthedocs.yaml in our root git folder. But we do not have such file.
Last time the build was successful was on July 16, 2023. (https://readthedocs.org/projects/avisynthplus/builds/21312134/ )
Then it failed on September 28th.

My questions: 
- I can't see any changes in readthedocs change log on requirements about .readthedocs.yaml. Then how did readthedocs formerly know, that our documentation config is placed in distrib\docs\english\source\conf.py  
- who is now the maintainer of our readthedocs?

**Comment by qyot27** [comment]
They could find conf.py just by scanning the directory.  Let me see if simply adding the configuration makes it start working again.
