### ISSUE TITLE
StrLen() wrong results for non-latin text.

### ISSUE THREAD

**Issue by Uzver123** [AviSynth/AviSynthPlus#373]
If i use **StrLen("Hello")** it works good returns 5, however if i use with non latin text, results are twice as large e.g. **StrLen("ЯЩЙ")** returns 6, not 3. Text i used is Cyrillic

As a workaround is there way to determine weather text is Latin?

Also function **UCase()** is not working with non Latin characters.

**Comment by pinterf** [comment]
Strlen is unaware of the real letter count, it returns the byte count in your case, because I suppose utf8 encoding is used there, which consumes two bytes in your language. See also:
https://forum.doom9.org/showthread.php?t=174459

As for Ucase: it works only for English characters.

**Comment by Uzver123** [comment]
Is there way to check weather language inside string is has latin or non latin characters?

There seems to be no support for regular expressions (regex) in AviSynth+ to strip all non latin characters from string and i don't know any other way of checking weather string is latin or other language.

**Comment by pinterf** [comment]
Or try StrToUtf8/StrFromUtf8 functions before StrLen, they convert a 8 bit (Ansi) string to UTF8 and back.

**Comment by pinterf** [comment]
Strlen is using byte count and cannot cope with utf8 text or with other unicode special features.
