### ISSUE TITLE
Subtitle x / y "-1" value is not working.

### ISSUE THREAD

**Issue by Uzver123** [AviSynth/AviSynthPlus#374]
Setting x / y to -1 does nothing meaningful.

From subtitle() help page:
**x, y** Text position. **Can be set to -1 to automatically center the text horizontally or vertically, respectively**.

**Comment by pinterf** [comment]
Thanks for the report, using -1 for centering is longer a valid option since fixing issue #293.
Documentations will be corrected accordingly; in general the Subtitle doc part must be refreshed, there are new parameters in 3.7.3 as well: bold, italic and noaa.

**Comment by pinterf** [comment]
Now works as intended, fixed the earlier inconsistent behavior; changed the documentation as well.
