### ISSUE TITLE
After upgrading to 3.7.3, does the GetChannel function need to be changed? There is no sound output.

### ISSUE THREAD

**Issue by lyturn** [AviSynth/AviSynthPlus#381]
This is my script.

--------------------------------------------------------------------
SetWorkingDir("c:\AviSynth+\plugins64+\")

v1 = FFmpegSource2("D:\video\v1.mp4",atrack=-2).TurnRight()
v2 = FFmpegSource2("D:\video\v2.mp4",atrack=-2).TurnRight()
a1=DirectShowSource("D:\video\v1.mp4")
a2=DirectShowSource("D:\video\v2.mp4")

b=BlankClip(length=5307,width=2160,height=1920,fps=29,channels=2,color=$000000)
xpos = 1080
ypos = 0
k=Overlay(b,v1)

video=Overlay(k,v2,x=xpos,y=ypos)

mono1=GetChannel(a1, 1).AmplifydB(7)
mono2=GetChannel(a2, 2).AmplifydB(2)

audio=mergechannels(mono1,mono2)

AudioDub(video,audio)
--------------------------------------------------------------------

**Comment by pinterf** [comment]
Are you sure that DirectShowSource returns the audio properly?
I found this one but otherwise dunno:
http://avisynth.nl/index.php/Internal_functions#OPT_UseWaveExtensible

**Comment by qyot27** [comment]
Could DSS and the re-introduced audio cache be having some kind of conflict?  Seeing as 3.7.2 is apparently fine and 3.7.3 isn't.

I certainly couldn't reproduce this with FFMS2 or Colorbars on Linux.

**Comment by pinterf** [comment]
Audio channel flags perhaps, haven't tried yet, could you reproduce it with arbitrary stereo source?

**Comment by pinterf** [comment]
Could not reproduce either. I've got sound. Need more info.
- The files v1.mp4 and v2.mp4 used above. Or a small file that would still fail.
-  "there is no sound output" Where? 1.) encoded the output with ffmpeg? 2.) playing the avs file using virtualdub2? 3.) playing through AvsPMod?

**Comment by pinterf** [comment]
Not reproducible, no answer on questions.
