### ISSUE TITLE
Bounds checking for audio

### ISSUE THREAD

**Issue by qyot27** [AviSynth/AviSynthPlus#43]
Despite the recent lack of activity, I figured it would still be a good idea to make a note of what seems to have happened with the resampling issue in the MT branch.

As per [FFMS2 #143](https://github.com/FFMS/ffms2/issues/143), which describes the issue that had also been discussed in the Doom9 thread, the response seems to be that the audio caches in AviSynth also performed bounds checking, and removing the caches in the MT branch correspondingly removed the checking, leading to the errors.

ResampleAudio doesn't have any checking, apparently, relying on the audio cache to do that (and the checking in SSRC must interact with the ones in the core in some way, because it also throws the error, but at the end of reading a stream rather than immediately at the beginning).

Is bounds checking something that should be separate from the caches, or does it need to be a package deal to ensure things work correctly?  Or is it more a decision that bounds checking should be plugin-side?

**Comment by pylorak** [comment]
Fixed by commit 318a13ad79ede9d5113fb624b9e0f8d2dda80687 .
