### ISSUE TITLE
ConvertToYV* functions: wrong chroma position?

### ISSUE THREAD

**Issue by erazortt** [AviSynth/AviSynthPlus#48]
- take a full HD clip in YV12, YV16 or YUY2 encoding
- compare the output of the following to scripts:

1:
Load(....)
UToY()

2:
Load(....)
ConvertToYV24()
LanczosResize(960,540)
UToY()

3:
Load(....)
YToUV(UToY8(), VToY8(), ConvertToY8().LanczosResize(960,540).ConvertToYV24())
UToY()
- (works equally well with all resize functions and with VToY() in last script line)
- zoom in like 400% and you see a shift of about 0.5 pixel to the left with the 2nd script relative to 1st and 3rd
- I would guess avisynth 2.5/2.6 have the same issue, though I havn't tested it

**Comment by innocenat** [comment]
Hello!

The default move for ConvertToYV24 is to assume MPEG2 chroma sitting for YV12. There is `ChromaInPlacement` parameter to set it to MPEG1 or DV mode.

If you pass in `ChromaInPlacement="MPEG1"` does it solve the shift problem?

**Comment by pinterf** [comment]
No answer, closed
