### ISSUE TITLE
Prefetcher object is not deleted in ScriptEnvironment destructor

### ISSUE THREAD

**Issue by chainikdn** [AviSynth/AviSynthPlus#50]
It's created in Prefetcher::Create() and then lives forever, which lead to:
- threads are not ended
- filter objects are not deleted

Fixed by adding `if (prefetcher) delete prefetcher;` to ScriptEnvironment::~ScriptEnvironment()

**Comment by pylorak** [comment]
Problem only seems to exist as a filter in 64-bit ffdshow.
http://forum.doom9.org/showthread.php?p=1712683#post1712683

**Comment by pylorak** [comment]
Seems to be an issue with ffdshow. Avs+ cannot completely prevent leaking with such misbehaving hosts, but commit 422aae83e0ba3b77fd066b6217b2cba7121f6010 at least avoid leaking VFBs which are the largest objects.
