### ISSUE TITLE
Access violation when using SelectEvery with negative offsets

### ISSUE THREAD

**Issue by torchlight** [AviSynth/AviSynthPlus#52]
Using SelectEvery(src,n,offset0,offset1,...) with negative offset values sometimes causes access violations.

This is the shortest script I found with which this behaviour can be consistently reproduced, which also causes access violations on Avisynth 2.5.8 and 2.6a4. (Reduced from a larger script which caused access violations only on Avisynth+ and not 2.5.8 or 2.6a4.)

```
BlankClip()
SelectEvery(1,0,0)
SelectEvery(1,-1)
```

**Comment by pylorak** [comment]
This crashes because GetFrame of Interleave (which is used internally by SelectEvery) falsely uses the C %-operator instead of calculating the correct congruent modulus for the child clip index. This results in a negative (and so out-of-bounds) indexing into the array.
