### ISSUE TITLE
SVP with AVS+

### ISSUE THREAD

**Issue by pylorak** [AviSynth/AviSynthPlus#57]
Choppy playback and possible video corruption. Discussion starts here: http://forum.doom9.org/showthread.php?p=1713360#post1713360

**Comment by pylorak** [comment]
Hi Chainik,

I tried to reproduce your issues described on d9, but I didn't get far because SVP when started immediately complains about not finding "SetMTMode". This makes it completely impossible to run SVP on Avs+, and thus to debug any problems on my side. Please advice on how to procede, otherwise I cannot do anything.

**Comment by pylorak** [comment]
Can you make an SVP version that doesn't try to use MT in avisynth at all? Just for testing. It would allow me to first isolate if the problems are specific to MT in avs+ or not. Should the single-threaded version work perfectly, a second step could be an SVP version that uses setfiltermtmode+prefetcher. Then I can debug further.

**Comment by pylorak** [comment]
I can confirm the stuttering happens with 6 or 11 threads.

**Comment by chainikdn** [comment]
This is because of real-time nature of ffdshow. When AVS requests from ffdshow some future frame that is not in the ffdshow buffers yet, it immediately returns the latest frame it got instead of waiting for the right frame. And AVS+ asks for future frames too early / aggresively. This leads to some run time artifacts depending on number of prefetched frames and (may be) current prefetcher pattern.

**Comment by pylorak** [comment]
I understand your point about ffdshow, and I didn't know it works that way. I think that is part of the problem. But how is that not a problem with e.g 12 threads, while it is with 6 threads? And why is it independent from the number of physical CPU cores? There is something I don't understand (or misunderstand), because then according to my logic the stuttering should be more and more likely as you increase the number of threads, and for the same number of threads it should be less likely as you increase the number of CPU cores.

**Comment by pylorak** [comment]
I just saw your new comments on the SVP forums. I'll be working the frame sequences through in detail when I get home from work. Maybe that will help clear up the missing things.

**Comment by pylorak** [comment]
Solved by 306afa4ab1c0925844c8d1a8f2f909b155534cb3. Discussion and explanation in http://www.svp-team.com/forum/viewtopic.php?id=2446 .
