### ISSUE TITLE
avisynth.h

### ISSUE THREAD

**Issue by Khanattila** [AviSynth/AviSynthPlus#61]
virtual void _stdcall ApplyMessage(PVideoFrame* frame, const VideoInfo& vi, const char* message, int size, int textcolor, int halocolor, int bgcolor) = 0;

_sdtcall is not ANSI.
__sdtcall is ANSI.

**Comment by tp7** [comment]
Does this actually affect anybody?

**Comment by Khanattila** [comment]
There are... 71 __stdcall and just one _stdcall.
Why keep the only thing different?
