### ISSUE TITLE
Serious speed regression sometime after r1765.

### ISSUE THREAD

**Issue by Reel-Deal** [AviSynth/AviSynthPlus#63]
Full details here: http://forum.doom9.org/showthread.php?t=168856&page=62#post1736090

QTGMC slows down drastically when using with any version after r1765. r1576 is faster/more efficient than any of the newer builds. Why is that r1576 uses more memory but fewer threads, while the newer builds use a lot less memory but more threads? Seems a bit odd...

**Comment by pylorak** [comment]
Speed regression fixed in merge 8edc8b1f8e3037477b523f2f84c167ffe5a5e388.
