### ISSUE TITLE
r2063 MT LNK4197 warning in 64bit build.

### ISSUE THREAD

**Issue by fuchanghao** [AviSynth/AviSynthPlus#78]
Visual studio 2015 update 3
Cmake 3.6.0

All happened in avisynth_c.obj,example

`严重性	代码	说明	项目	文件	行	源	项目级别	禁止显示状态
警告	LNK4197	多次指定导出“avs_is_yv24”；使用第一个规范	AvsCore	D:\Source code\AviSynthPlus\Build x64\avs_core\avisynth_c.obj	1	生成	3`

**Comment by pylorak** [comment]
This is a known warning, but it is harmless. Theoretically it should go away if the linker definition file is left out of the 64-bit build. Unfortunately it is needed for i386. So the fix will likely come in a change to the CMakeFile.
