### ISSUE TITLE
BitsPerPixel not reporting correct size for Alpha formats

### ISSUE THREAD

**Issue by qyot27** [AviSynth/AviSynthPlus#92]
For YUV444P16, it reports 48, like expected.
For YUVA444P16, it reports 48.

I noticed this while testing FFmpeg again.  Any of the alpha formats would crash it with invalid buffer sizes if only BitsPerPixel was used, while specifically accounting for the alpha channel (by using `BitsPerComponent * NumComponents`, `BitsPerPixel * BitsPerComponent / 8 * NumComponents`, or the much more compact `BitsPerPixel + BitsPerComponent` since I knew it wasn't allotting the 4th channel only) allowed it to work and output an image.

**Comment by pinterf** [comment]
Fixed
