### ISSUE TITLE
some source files are not UTF-8 format.

### ISSUE THREAD

**Issue by fuchanghao** [AviSynth/AviSynthPlus#93]
.\plugins\TimeStretch\SoundTouch\PeakFinder.cpp
.\plugins\Shibatch\shibatch.cpp
.\plugins\Shibatch\ssrc.h
.\plugins\Shibatch\supereq.cpp
.\plugins\Shibatch\supereq.h

ANSI

.\plugins\Shibatch\ssrc.cpp

Shift-JIS

**Comment by chikuzen** [comment]
I send a PR about this issue.
https://github.com/AviSynth/AviSynthPlus/pull/96

**Comment by fuchanghao** [comment]
thanks

**Comment by fuchanghao** [comment]
Still have problems in 
.\avs_core\filters\turn.cpp

ISO 8859-2

PS: why changed to utf8 with BOM not without BOM.

**Comment by chikuzen** [comment]
> why changed to utf8 with BOM not without BOM.

Because we are using VisualStudio.
VisualStudio doesn't like UTF8 without BOM.

**Comment by chikuzen** [comment]
I'm now implementing some codes to support the new format  on turn.cpp.
This issue will be solved by them at the same time.

**Comment by pinterf** [comment]
I can see no problem, closed
