### ISSUE TITLE
avisynth_c.h: cstddef header on C

### ISSUE THREAD

**Issue by Kamekameha** [AviSynth/AviSynthPlus#97]
The `cstddef` header file is intended for C++, therefore avisynth_c.h is now unusable for C plugins (or whatever written in pure C interfacing with this header), raising syntax errors or file not found when compiling. An `#if __cplusplus` clause around that include on avs/types.h should be enough I guess. Too lazy to test and make a pull request :^).

Introduced in a616181c63164d3d79f72e4a60a2d1ea40b5bbbc.

**Comment by pylorak** [comment]
Whoops, sorry. I didn't think about it being included in C headers too, my bad. Will make a fixing commit soon (after work).

**Comment by Kamekameha** [comment]
Nice, thanks.
